### PR TITLE
issue_1519 fixed

### PR DESCRIPTION
**Pull request by PrakashDurlabhji**

### CODE REVIEW

**Comment by ThomasKranitsas** [comment]
@PrakashDurlabhji this only fixes the `textareas`. Can you also make the placeholder of `input` as well as `select` elements `capitalize` instead of `uppercase`?

**Comment by ThomasKranitsas** [comment]
@PrakashDurlabhji this only fixes the `textareas`. Can you also make the placeholder of `input` as well as `select` elements `capitalize` instead of `uppercase`?

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas i feel it did all.ok updating immediately.

**Comment by ThomasKranitsas** [comment]
any update on this one?

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas please give me 20minutes.updating PR

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas Pr updated.

**Pull request merged**
