### PR TITLE
Ticket ##1491 - There is no 'Add link' button for adding a new extern…

### PR DESCRIPTION
**Pull request by nauhil**
Added 'Add Link' button in desktop

### CODE REVIEW

**Comment by ThomasKranitsas** [comment]
@nauhil can you please fix the failing tests?

**Comment by nauhil** [comment]
OK. Let me check

**Comment by nauhil** [comment]
@ThomasKranitsas Please review it

**Comment by ThomasKranitsas** [comment]
Perfect!

**Pull request merged**
