### PR TITLE
MSFT 178 issue#2850 - added border on view more challenges button focus state

### PR DESCRIPTION
**Pull request by romitgit**
issue #2850

### CODE REVIEW

**Comment by romitgit** [comment]
Whis is this blocked? Something needed from my side?

**Comment by veshu** [comment]
@romitgit The target branch is wrong. Please adjust the PR to sent to qa-accessbility branch.

**Comment by codeMinter** [comment]
@romitgit don't worry I have fixed it, just make sure you use right target branch for future PR

**Comment by romitgit** [comment]
> @romitgit don't worry I have fixed it, just make sure you use right target branch for future PR

Thanks @codeMinter

**Pull request merged**
