### PR TITLE
issue 2396 fix - add profile submenu and expand top level menu if use…

### PR DESCRIPTION
**Pull request by ya3ya6**
### Issue 2396 fix
**Description :** add profile submenu and expand top level menu if user is logged in
**Changes :**

- Profile submenu is added on both default and production config files.
- User status is added to TopNavRef component attributes.

NOTE: This doesn't work without this pull request: https://github.com/topcoder-platform/navigation-component/pull/20

### CODE REVIEW

**Comment by ya3ya6** [comment]
@luizrrodrigues

Pr updated.

Changes:
- Removed "Payments" and "All projects" from account dropdown menu.
- Changed The name of Level2 Menu From "Profile" To "Dashboard":

image

- fixed CircleCI issue.

**Comment by luizrrodrigues** [comment]
@ya3ya6 Sorry, maybe some confusion here.

- Dashboard
- My Profile
- Payments

These need be secondary menu of Work

**Comment by luizrrodrigues** [comment]
- Work
    - Dashboard
    - My Profile
    - Payments
- Compete
    - All challenges
    - Competi...

**Comment by ya3ya6** [comment]
> * Work
>   
>   * Dashboard
>   * My Profile
>   * Payments
> * Compete
>   
>   * All challenges
>   * Competi...

oops. i don't think so. the request come from : https://github.com/topcoder-platform/community-app/issues/2396#issuecomment-498444734

he said that we need a level 2 navigation. work is level 1 menu, Compete, Tracks, Community are level 2 menues(secondary menues), "All challenges" and "competitive programming" and etc are level 3 menues. (this terminology of level 1 menu and level 2 (secondary) menus are in source code.)

a level 2 (secondary) menu under work means a level 2 menu under work just like "compete" and "tracks". you can see the Work is bolded in design, and when you click it it will expand (which means its parent of compete, tracks, community), and also in menu model its parent of compete and tracks and community (search "HEADER_MENU" on here to see the menu model: https://github.com/topcoder-platform/community-app/blob/feature-new-nav/config/default.js)
So menu is not structured as you said in this comment (work is a level 1 menu and its parent of compete and tracks which are level2. but in your structure work is not parent of compete and tracks).

adding a completely different menu inside a level 1 menu (work) is not compatible with "menu model" and also "design", and it needs alot of change in structure of menu.

I beleive that @vic-tian meant this, and i thought you meant this as well before.

It's ok if you insist that the menu should be like that, but It will be good if you can ask about it from @vic-tian who suggest this, cause i think you misunderstood him.

**Comment by luizrrodrigues** [comment]
I see, I'll get confirmation

**Comment by ya3ya6** [comment]
@luizrrodrigues 
Thanks .

also i said terminology of level 1 and level 2 and level 3 menus are in source code , it's in here: https://github.com/topcoder-platform/navigation-component/blob/develop/src/components/TopNav/index.js

**Pull request closed without merging**
