### PR TITLE
Issue 3246 fix

### PR DESCRIPTION
**Pull request by PrakashDurlabhji**

### CODE REVIEW

**Comment by veshu** [comment]
@PrakashDurlabhji could you please fix the tests as well?

**Comment by PrakashDurlabhji** [comment]
@veshu PR updated

**Comment by veshu** [comment]
@PrakashDurlabhji please check the video https://take.ms/iRy3j . This fix doesn't fixes two issues:
1. Still handle and profile pic is treated two different control. I can focus on both separately.
2. When pressing tab to go to search icon, search box is not shown. Probably on blur is not working on handle/profile pic control.

Note: Bug bash is closing on 8PM EST, 5 Sept. If this is not fixed by then it will be closed. 
Thanks!

**Comment by PrakashDurlabhji** [comment]
@veshu commente on issue with screenshots

**Pull request merged**
