### PR TITLE
issue 2886 fix

### PR DESCRIPTION
**Pull request by PrakashDurlabhji**

### CODE REVIEW

**Comment by gurmeetb** [comment]
@PrakashDurlabhji same issue

**Comment by gurmeetb** [comment]
@PrakashDurlabhji `Contrast ratio should be 4.5:1` - check using Google Chrome extension. 

2886_Contrast

**Comment by PrakashDurlabhji** [comment]
@gurmeetb i guess this issue is only to those whose topcoder handle name is in grey color, and not for other limits.
ticket mentioned to just change grey color and not others. 

can you please confirm?

**Comment by PrakashDurlabhji** [comment]
@gurmeetb I will update other values too, but can you please provide hex values for each limit, because I installed that extension, but not able to understand how to use it.

**Comment by gurmeetb** [comment]
@PrakashDurlabhji to use it, when on that page click extension, it will show tabular info for Accessibility like it does, each of which matches the respective fields on page. So if that has green check means it is valid based on Accessibility contrast. Hope this helps.

**Comment by gurmeetb** [comment]
@veshu please suggest @PrakashDurlabhji ☝️ on what are the alternative options, if any.

**Comment by veshu** [comment]
@gurmeetb @PrakashDurlabhji For color contrasts issues we can get help from @Dara-K where she will guide to choose the color without loosing branding of the site.

@PrakashDurlabhji Please enroll the @Dara-K if you need the color that can be used.

**Comment by Dara-K** [comment]
Hi @PrakashDurlabhji ,

For the gray handle please use  #555555 and for the green handle #2D7E2D.

**Comment by codeMinter** [comment]
@veshu this looks good, please deploy for QA verification.

**Pull request merged**
