### PR TITLE
MSFT-125

### PR DESCRIPTION
**Pull request by r0hit-gupta**
Changes for #2823

### CODE REVIEW

**Comment by veshu** [comment]
@r0hit-gupta please check below:
1. Table should be aria-label with "Registrants"
2. Design is broken now, please check the live version to compare
3. https://www.w3.org/TR/wai-aria-practices/examples/table/table.html Please see here for more info
4. When I reach to second row it still says 0 rows(for all rows)

**Comment by r0hit-gupta** [comment]
@veshu try this now. Also, please let me know which screen reader are you using. I have used https://www.w3.org/TR/wai-aria-practices/examples/table/table.html as a reference.

**Comment by veshu** [comment]
@r0hit-gupta I am using NVDA and mac(Voice Over) too. I will check the updates. Thanks!

**Comment by veshu** [comment]
@r0hit-gupta Using NVDA it doesn't read the column name of 2 and 3 when reading cell value.

For username it says column "username" but not for other columns it just read as "column 2" and "Column 3" respectively 

https://streamable.com/vrehg

**Pull request merged**
