### PR TITLE
New settings profile

### PR DESCRIPTION
**Pull request by dedywahyudi**
@birdofpreyru 

Please check this PR, i just fix the PR conflicts. 
Let me know what you think. 

cc @cwdcwd @urwithat @ThomasKranitsas

### CODE REVIEW

**Comment by birdofpreyru** [comment]
@dedywahyudi a snapshot test fails after you last commit. Otherwise, if you checked that my comments from the previous review have been addressed, and double-checked that it works, I'm fine to merge.

**Comment by dedywahyudi** [comment]
@birdofpreyru Nice, thanks
Latest commit should pass the circle ci test

**Comment by liuliquan** [comment]
@birdofpreyru I've moved the auth0 client id to ENV config: DEV_AUTH0_CLIENT_ID and PROD_AUTH0_CLIENT_ID

**Comment by dedywahyudi** [comment]
@birdofpreyru @liuliquan  
Are we good with this PR?

**Comment by birdofpreyru** [comment]
Are you waiting me to check / merge it?

**Comment by dedywahyudi** [comment]
Yes, if possible need check and merge

**Comment by birdofpreyru** [comment]
@dedywahyudi ok, merged and deployed to dev environment, please check

**Comment by dedywahyudi** [comment]
@birdofpreyru Awesome, thanks a lot!

**Pull request merged**
