### PR TITLE
Updates from Settings Profile - Account Challenge

### PR DESCRIPTION
**Pull request by dedywahyudi**
@birdofpreyru 

Here's the updates from Topcoder Settings Profile - Account Challenge
Attached the patch file. This PR already applied the patch.

[new-develop.patch.zip](https://github.com/topcoder-platform/community-app/files/2175669/new-develop.patch.zip)

FYI: Not include the Email Verification bus Event yet.

cc @ThomasKranitsas @cwdcwd @urwithat

### CODE REVIEW

**Comment by dedywahyudi** [comment]
community-app/__tests__/shared/utils/markdown.js
  3:1   error  'postcss' should be listed in the project's dependencies. Run 'npm i -S postcss' to add it  import/no-extraneous-dependencies
  3:10  error  'Stringify' is defined but never used no-unused-vars

FYI: These 2 errors coming from @birdofpreyru latest commit, we leave the errors as it is.

**Comment by birdofpreyru** [comment]
Yeah, sorry about that, VSCode's autofill automatically added that import when I was adding {String} param to documentation of test method, and I have not noticed it :)

**Comment by dedywahyudi** [comment]
No problem! :)

**Comment by dedywahyudi** [comment]
@birdofpreyru wondering this is package-lock.json conflict coming from new-develop? We not touch anything.

**Comment by birdofpreyru** [comment]
That's fine, just fix it doing the merge on your machine, overwriting `package-lock.json` with either your version, or the one from **new-develop**, then do `npm install` and commit the resulting `package-lock.json`.

**Comment by dedywahyudi** [comment]
Thanks, conflicts fixed now.

**Pull request merged**
