### PR TITLE
Issue 2185 fix

### PR DESCRIPTION
**Pull request by Gauravseta**

### CODE REVIEW

**Comment by ThomasKranitsas** [comment]
This is not fixed. The buttons should match

Screenshot 2019-03-23 at 15 16 07

**Comment by Gauravseta** [comment]
with same text "Upload a new avatar"?

**Comment by ThomasKranitsas** [comment]
Same text and same style please

**Comment by ThomasKranitsas** [comment]
One last change (hopefully). Please remove the fixed width.

Screenshot 2019-03-25 at 11 01 04

**Comment by ThomasKranitsas** [comment]
@Gauravseta any update here?

**Comment by Gauravseta** [comment]
@ThomasKranitsas oh sorry just 5 mins.

**Comment by Gauravseta** [comment]
@ThomasKranitsas kindly can you please check?

**Pull request merged**
