### PR TITLE
MSFT-124

### PR DESCRIPTION
**Pull request by r0hit-gupta**
Changes for #2822

### CODE REVIEW

**Comment by codeMinter** [comment]
@sushilshinde @nkumar-topcoder **NOTE** -  this is fix for 2 issues.

**Comment by sushilshinde** [comment]
@r0hit-gupta @codeMinter please do not follow this practice

I want two separate PRs, I have to track fixes till the production deployment.

**Comment by sushilshinde** [comment]
@r0hit-gupta @codeMinter 

https://github.com/topcoder-platform/community-app/pull/2947#issuecomment-514613904

**Comment by codeMinter** [comment]
@sushilshinde got it. 

@r0hit-gupta can you kindly make 2 PRs, I will close this so we don't merge this.

**Comment by r0hit-gupta** [comment]
@codeMinter the changes are only for a single issue. Coincidentally, it also fixes an another issue. Should I make separate PRs with the same changes?

**Comment by veshu** [comment]
@codeMinter @sushilshinde The same  fix for two issue? please reconfirm. Thanks!

**Comment by codeMinter** [comment]
https://github.com/topcoder-platform/community-app/issues/2829#issuecomment-515562604

**Comment by r0hit-gupta** [comment]
@codeMinter I have marked the one issue as duplicate. How to proceed?

**Pull request merged**
