### PR TITLE
Fix issue #287

### PR DESCRIPTION
**Pull request by elfman**
Fix issue #287

### CODE REVIEW

**Comment by birdofpreyru** [comment]
@elfman Nope, we can do better. The problem with this default avatar in the tooltip is that the logic to show it is really goofy: it always tries to load the photo, and if it fails due to 404 error, then it updates the URL to the default avatar in the error handler.
1. There should be no errors: if winner object has no photo URL - we just use the default avatar immediately; if he has absolute photo URL - we use it; if the URL is relative (like `/i/m/some-avatar.jpg`), it should be prepended with the correct domain (now, when I am running locally, it goes to `local.topcoder.com/i/m/some-avatar.jpg`, which is wrong, thus fails).
2. We have a standard component for rendering avatars: https://github.com/topcoder-platform/community-app/blob/develop/src/shared/components/Avatar/index.jsx which basically takes care  about styling. For the usecase in the listing, I guess, just the default theme of that component is the same, so we should reuse that.

**Comment by elfman** [comment]
@birdofpreyru Updated as your suggestion, except the theme of avatar. The default avatar theme is so small, I change it bigger

**Comment by birdofpreyru** [comment]
@elfman Well, but do we really need the `onError` handler? I would expect we don't, cause if we compose avatar URLs in the correct way (adding the right base domain from configuration) then all URLs gonna be just correct.

**Comment by birdofpreyru** [comment]
So, no need to modify avatar component then

**Comment by elfman** [comment]
@birdofpreyru I have composed the URLs in line 36 of `UserAvatarTooltip/index.js`. Adding `handleError` is just wanna to show a default avatar when some network error happen, in case there would be empty area.

**Comment by birdofpreyru** [comment]
@elfman Hmm... I prefer to remove error handlers. If the page fails due to network error, broken avatar images is the least of the problems, as most probably it will also break everything else. So, no need for such complication of the code.

**Comment by elfman** [comment]
@birdofpreyru Updated, please check.

**Comment by elfman** [comment]
@birdofpreyru Currently on `origin/develop`, `ChallengeList` does not work when there is no query string, this is not introduced by me

**Comment by birdofpreyru** [comment]
@elfman Btw, have you seen my last post in the challenge forum? I don't know what is your TC nickname to be able to pay for the Bug Hunt part of the challenge.

**Comment by elfman** [comment]
@birdofpreyru sorry, my TC nickname is `windyluo`

**Pull request merged**
