### PR TITLE
changes for #2840

### PR DESCRIPTION
**Pull request by anonymousjaggu**
changes

### CODE REVIEW

**Comment by codeMinter** [comment]
@anonymousjaggu I cannot select checkbox when focussed on it using tab.

**Comment by anonymousjaggu** [comment]
@codeMinter MR updated please check

**Comment by codeMinter** [comment]
@anonymousjaggu please fix lint and tests before marking for Review.

**Comment by codeMinter** [comment]
> @anonymousjaggu please fix lint and tests before marking for Review.

@anonymousjaggu if you are not responding on recurring issues within 4 hrs, the ticket will be marked for PICKUP for others.

**Comment by anonymousjaggu** [comment]
Hi @codeMinter I will update the MR

**Comment by codeMinter** [comment]
@anonymousjaggu there has been no update on MR fix for more than 24 hrs so this goes for Open as per Bug Bash rules.

**Pull request closed without merging**
