### PR TITLE
[$50] - Next Deadline msg on Challenge Details page for past challenges #445 #700

### PR DESCRIPTION
**Pull request by imadx**
added `late by <duration>` for late challenges..

### CODE REVIEW

**Comment by birdofpreyru** [comment]
When I have tried to merge in the latest develop, I've ended up with this layout:

image

Please check and correctly merge *develop* into your PR.

There is another conflict inside Header/index.jsx, around the line 115
For that piece, I am pretty sure it should be (while you have been working this issue, I've updated the code there to use `MomentJS` instead of JS Date):
```
  const deadlineEnd = moment(nextPhase && nextPhase.scheduledEndTime);
  const currentTime = moment();

  let timeLeft = deadlineEnd.diff(currentTime);
  let behindSchedule = (timeLeft < 0);
  timeLeft = Math.abs(timeLeft);
```

**Comment by imadx** [comment]
I'll check.. (y)

**Comment by imadx** [comment]
@birdofpreyru Fixed the merge conflicts :+1:

**Comment by birdofpreyru** [comment]
@imadx Ok, now I go to the dev env and the very first challenge I see in the listing is:
image
I check the details page:
image
:(

**Comment by imadx** [comment]
@birdofpreyru  Can you check now? https://github.com/topcoder-platform/community-app/pull/749/

**Pull request closed without merging**
