### PR TITLE
issue 2828 fix

### LINKED ISSUE #2828: [$20][MSFT-131] [Challenge Page] Prizes section is not readout by the screen reader
**Steps to Reproduce**
1. Go to https://www.topcoder.com/challenges/30095032
2. Switch on the screen reader
3. Tap on the page header and press tab button until it reaches to the prizes section
2. Listen

**Expected Result**
It should be read-out by the screen reader

**Actual Result**
Prizes section is not read out by the screen reader

**Device**: Desktop/Labtop
**Operating System**: Windows
**Browser**: Chrome

**WCAG Category**: 1. Perceivable
**WCAG Level**: A
**WCAG Success Criterion**: 1.3.1 Info and Relationships
**Screen Reader Used**: JAWS
**Accessibility Audit Tool used**: N/A

**Attachment**
https://topcodermsft-my.sharepoint.com/personal/pd-topcoder_topcodermsft_onmicrosoft_com/Documents/Forms/All.aspx?cid=6aa53cde%2D1eef%2D4bae%2Dbfe5%2Df5f5f79e9df4&FolderCTID=0x0120005C598A51049FC14CBA882E1AEE168F51&id=%2Fpersonal%2Fpd%2Dtopcoder%5Ftopcodermsft%5Fonmicrosoft%5Fcom%2FDocuments%2FMSFT%2DTeams%2DQA%2FJune%202019%2F29%20Jun%2FTest%20Results%2FBug%20Videos%20%26%20Log%20Files%2Fcodejam%2DAccessibility%2F41

### PR DESCRIPTION
**Pull request by PrakashDurlabhji**
#2828 fix

### CODE REVIEW

**Comment by gurmeetb** [comment]
@PrakashDurlabhji please fix all issues before marking `ready for review`.

**Comment by codeMinter** [comment]
@PrakashDurlabhji doesn't looks like we have tab enabled for Prizes. I have tried this on Windows and Mac both, there is no tab for Prizes. We need to enable tab for Prizes too.

**Comment by PrakashDurlabhji** [comment]
@codeMinter updating it

**Comment by codeMinter** [comment]
@PrakashDurlabhji Please flag where are we on this? I will wait for next 4 hrs for new PR with fix, after which will need to open this for others.

**Comment by PrakashDurlabhji** [comment]
@codeMinter just a minor change it should be update in few minutes

**Comment by PrakashDurlabhji** [comment]
@codeMinter @veshu PR updated

**Comment by veshu** [comment]
@PrakashDurlabhji Please check the tests are failing.

**Comment by codeMinter** [comment]
@PrakashDurlabhji any reason why you add `role="button" ` ?

**Comment by PrakashDurlabhji** [comment]
@codeMinter i guess link will do.

**Comment by PrakashDurlabhji** [comment]
@codeMinter Pr updated

**Comment by codeMinter** [comment]
> @codeMinter i guess link will do.

It is neither a link. I will research and suggest what should it be, but I guess since you are working on it, please can you look up Accessibility guidelines what you do for labels? It is just a label. 

`Going ahead, please do not mark for review unless everything is GREEN on PR,  you might loose access to this repo else. `

**Comment by PrakashDurlabhji** [comment]
@codeMinter sorry for it, I will make sure it wont happen again, but link shall do I feel

**Comment by veshu** [comment]
@PrakashDurlabhji Your fix is breaking on automated test, please ensure they are passing. Thanks!

**Comment by codeMinter** [comment]
@PrakashDurlabhji do not assign ticket to yourself, you cannot keep ticket forever.

**Comment by PrakashDurlabhji** [comment]
@codeMinter ya I understand I cannot keep ticket myself, but isnt this working  as expected?

**Comment by codeMinter** [comment]
@PrakashDurlabhji plz do not open PRs for tickets not owned by you

**Comment by PrakashDurlabhji** [comment]
@codeMinter let me see circleCI build job now. I will close PR again after that.

**Comment by codeMinter** [comment]
@PrakashDurlabhji run it locally.  You cannot open PR and push commits,  you are putting unnecessary load on our servers.

**Comment by PrakashDurlabhji** [comment]
@veshu waiting for your take on above issue. where a person delibaterly takes someone else issue which is made open, while he could have taken other issues which are open, though previous feedbacks are already pending for his current going issue, and PR is copied too.
Did not experience such biased decisions by reviewers

@codeMinter @r0hit-gupta

**Comment by crazyk07** [comment]
Hi @PrakashDurlabhji, there seems to be a misunderstanding here and Rohit has wrote an explanation in the ticket you are discussing.  Our reviewers are just following procedure with code reviewing, I currently do not detect any bias.  There could have been something procedural that was overlooked (Since we are dealing with 170 tickets initially), but there is nothing intentional here.  If you want to discuss further, please raise a ticket with topcoder support and tag me onto the message (glenn.kozawa@topocder.com).  Would prefer to move the conversation outside this thread for better accountability.  I have a low likelihood of responding within github due to the high volume of tickets we are looking at.

**Pull request closed without merging**
