### PR TITLE
Add Basic Info Updates, Skill, Community

### PR DESCRIPTION
**Pull request by nauhil**
TODO
1. register/unregister, add/remove member to group (community-app)
2. move service/memberCert.js to topcoder-react-lib (community-app, topcoder-react-lib)
3. add unregister community function to backend (topcoder-react-lib)
4. add remove member from group function to backend (topcoder-react-lib)

@ThomasKranitsas please review it

### CODE REVIEW

**Comment by ThomasKranitsas** [comment]
@nauhil I'm testing with the `TonyJ/appirio123` account and I'm getting the following error http://take.ms/geRHb

Can you please check it?

It seems related to the `addresses` property

**Comment by nauhil** [comment]
TonyJ's basic_info trait from backend response [https://monosnap.com/file/5LMju5tCchJZxB9LRBrRFFze6jLNUW](https://monosnap.com/file/5LMju5tCchJZxB9LRBrRFFze6jLNUW)

huanner's basic_info trait, this account is my old testing account, before ap_member_service updated, I used this account.  response has two address fields
[https://monosnap.com/file/9NAKBeWGmX3eKdEW4ommWSwNLL2Min](https://monosnap.com/file/9NAKBeWGmX3eKdEW4ommWSwNLL2Min)

This account that I created new account for testing new basic info function after ap_member_service updated, that's correct response
[https://monosnap.com/file/KHZaT1JTdPVW02u8b728KQn8StbDBv](https://monosnap.com/file/KHZaT1JTdPVW02u8b728KQn8StbDBv)

**Comment by ThomasKranitsas** [comment]
@nauhil  I think we just need to handle the situation where the `addresses` property is missing from the response.
The frontend should not expect this to be present as it'll also not be there for new accounts.

Once the user saves his/her profile, that field should get populated.

Can you please take care of that?
Consider this as a private task and not as a final fix. I'll process an additional payment for that.

**Comment by ThomasKranitsas** [comment]
I believe it is

**Pull request merged**
