### PR TITLE
Fix for issue #1801

### PR DESCRIPTION
**Pull request by gurmeetb**

### CODE REVIEW

**Comment by sushilshinde** [comment]
@gurmeetb please fix the tests

**Comment by gurmeetb** [comment]
ah sorry, looking now

**Comment by sushilshinde** [comment]
@gurmeetb 

This requirement is for private communities 

https://topgear.topcoder-dev.com

dan_developer/dantopcoder123

**Comment by sushilshinde** [comment]
Closing PR, needs re-work

**Pull request closed without merging**
