### PR TITLE
Fix #3118 - Focus on Elements via Tab Key on Accessibility Webpage

### LINKED ISSUE #3118: [$40] Focus on Elements via Tab Key on Accessibility Webpage
Many instances of this occurring were reported in a previous bug hunt.  These tickets have been condensed to this one ticket.  The main idea for this ticket is that a user should be able to tab to all the various elements on [this webpage](https://www.topcoder.com/community/accessibility-testing).

In order to complete this ticket, make sure each of these tickets are satisfied:

#3112 - Search Bar
#3111 - Tracks Submenu
#3110 and #3070  - Support Button (blue outline) / Attachments
#3109 - Topcoder Handle (Ignore Search as it is being handled in 3112)
#3108 - Community and Compete
#3107 - Submenus

### PR DESCRIPTION
**Pull request by fikzzzy**

### CODE REVIEW

**Comment by sexta13** [comment]
@tc-mfikria can you please fix the conflicting files and check the CI tests?

**Comment by sushilshinde** [comment]
@sexta13 @tc-mfikria Please resolve conflicts

**Comment by sushilshinde** [comment]
How can you check-in this :)

**Comment by mfikria** [comment]
@sushilshinde sorry forgot to clean up

**Comment by sushilshinde** [comment]
> @sushilshinde sorry forgot to clean up

No problem, just joking.

**Comment by tc-mfikria** [comment]
@sushilshinde @ajefts should be fixed now.  except #3110 and #3070 cannot be fixed because the attachment field/button is in zendesk form which is not in community-app. It is fetch and initialized directly from topcoder.zendesk.com

**Comment by crazyk07** [comment]
@sexta13  Can you check on this?  not sure if this has been resolved or not

**Comment by sexta13** [comment]
> @sexta13 Can you check on this? not sure if this has been resolved or not

I'll give it a check

**Comment by sexta13** [comment]
Still has some issues. Can't navigate in submenu using left-right arrow keys.

When using tab along the page it has some strange behaviours: when goes to handle, then I click tab it goes to search, I click tab again it comes back to handle, i click tab goes to search and then if I click tab finally goes forward.

**Pull request closed without merging**
