### PR TITLE
issue_1539 fixd

### PR DESCRIPTION
**Pull request by Gauravseta**

### CODE REVIEW

**Comment by Gauravseta** [comment]
@ThomasKranitsas saw errors on circleci for npm test, m sure errors are not failing due to my change, and those are already present in develop branch

**Comment by ThomasKranitsas** [comment]
@Gauravseta you should run `npm run jest -- -u` to fix the snapshot.

**Comment by ThomasKranitsas** [comment]
@Gauravseta can you please fix this?

**Comment by Gauravseta** [comment]
@ThomasKranitsas ok running it. then shall i update PR again?

**Comment by ThomasKranitsas** [comment]
yes, please. Just run `npm run jest -- -u` and then commit the changes to this PR

**Comment by Gauravseta** [comment]
@ThomasKranitsas there are many error messages in red, though showing PASS label in every test suite.
also all are console errors. and i dont think its due to just my simple name changes.
i will run same command against develop branch and see what happens

**Comment by ThomasKranitsas** [comment]
nvm.. I've fixed that

**Pull request merged**
