### PR TITLE
Add filestack-js library

### PR DESCRIPTION
**Pull request by nahidshahin**
The only build error I got locally for 

`npm run build:dev`

`npm run build`

is `Error: Can't resolve 'filestack-js'`

After adding filestack-js library, the build works.

### CODE REVIEW

**Comment by ThomasKranitsas** [comment]
I see a lot of failing tests but I'm not sure if those are from your PR.

**Comment by nahidshahin** [comment]
Those test fail was there from before and I guess not part of issues-1727

**Comment by sushilshinde** [comment]
Testing now @nahidshahin will be back in sometime.

**Comment by nahidshahin** [comment]
sure thanks

**Pull request merged**
