### PR TITLE
fix #3101

### LINKED ISSUE #3101: [$10][FAST-1] The <html> element does not have a lang attribute
**Steps to Reproduce**
1. Go to https://www.topcoder.com/community/accessibility-testing
2. Right click > Inspect Elements 
3. Check the HTML tag

**Expected Result**
Ensures every HTML document has a lang attribute

**Actual Result**
The <html> element does not have a lang attribute

**Device**: Desktop/Labtop
**Browser**: Chrome

**WCAG Category**: 3. Understandable
**WCAG Level**: A
**WCAG Success Criterion**: 3.1.1 Language of Page
**Screen Reader Used**: N/A
**Accessibility Audit Tool used**: N/A

**Attachment**
https://topcodermsft-my.sharepoint.com/personal/msft-copilots_topcodermsft_onmicrosoft_com/Documents/Forms/All.aspx?cid=0bf9d0fe%2Dbdaa%2D4af3%2Dad48%2Dd3fa9f0e20e1&FolderCTID=0x0120005C598A51049FC14CBA882E1AEE168F51&id=%2Fpersonal%2Fmsft%2Dcopilots%5Ftopcodermsft%5Fonmicrosoft%5Fcom%2FDocuments%2F%5BFAST%5D%20Test%20for%20Accessibility%20Series%2Fcodejam%2F1

### PR DESCRIPTION
**Pull request by zjuasmn**
upgrade topcoder-react-utils to 0.7.9, <html> element should have a lang attribute

fix topcoder-platform/community-app#3101

### CODE REVIEW

**Comment by veshu** [comment]
@zjuasmn Test is failing could you please check this?

**Comment by zjuasmn** [comment]
@veshu I am checking.

**Comment by veshu** [comment]
@zjuasmn Also I see this is related to contentful issue. Please add Contentful lable on PR as well. Thanks!

**Comment by zjuasmn** [comment]
@veshu I cannot fix this issue, topcoder-react-utils are responsible for server side rendering,  the issue about <html> lang attribute has been fixed in https://github.com/topcoder-platform/topcoder-react-utils/commit/9e01fa2de1110fd8255f59d6cafbb89c798ad281, 
But versions in https://github.com/topcoder-platform/topcoder-react-utils is chaos.

Should I close this PR and mark the issue Open for pickup?

**Pull request closed without merging**
