### PR TITLE
Disable form on save

### PR DESCRIPTION
**Pull request by r0hit-gupta**
Fixes issue #2231

### CODE REVIEW

**Comment by ThomasKranitsas** [comment]
Please remove the console.log() statements

**Comment by r0hit-gupta** [comment]
I have updated the PR. Please review.

**Comment by ThomasKranitsas** [comment]
are all those changes required or you just reformatted the code?

**Comment by r0hit-gupta** [comment]
@ThomasKranitsas Its just the reformatting. There were indentation issues in the code.

**Comment by ThomasKranitsas** [comment]
Can you please resolve the merge conflicts?

**Comment by r0hit-gupta** [comment]
Resolved. Please review.

**Comment by r0hit-gupta** [comment]
Resolved merge conflicts. Please review.

**Comment by ThomasKranitsas** [comment]
Was all this reformatting really required? We were not getting any errors before so I'm not really sure why you changed the format. It's making it hard to review the actual fix.

Can you please reset the formatting and just leave the changes that fix the bug?

Thank you

**Comment by r0hit-gupta** [comment]
@ThomasKranitsas the ESLint tests were failing earlier. I had to add a HTML element almost at the parent level of every component, thus indenting every child element below. This indenting is necessary to pass the ESLint tests.

**Pull request closed without merging**
