### PR TITLE
MSFT-30

### PR DESCRIPTION
**Pull request by r0hit-gupta**
changes for #2752

### CODE REVIEW

**Comment by r0hit-gupta** [comment]
Please retrigger the build. The build failed due to some internal error on Circle CI.

**Comment by codeMinter** [comment]
@r0hit-gupta please fix failing tests and move change to `react-ui`.

**Comment by r0hit-gupta** [comment]
@codeMinter done

**Comment by sushilshinde** [comment]
PR id fo `react-ui`, please link such PRs

**Comment by codeMinter** [comment]
> PR id fo `react-ui`, please link such PRs

Uses exiting variable so no PR for it.

**Comment by sushilshinde** [comment]
@r0hit-gupta when there is not dependency dont label :)

**Comment by r0hit-gupta** [comment]
@sushilshinde which label are you talking about? I did not add any.

**Comment by sushilshinde** [comment]
> @sushilshinde which label are you talking about? I did not add any.

Sorry I wanted to tag @codeMinter :)

**Comment by sushilshinde** [comment]
@r0hit-gupta @codeMinter can you resolve conflicts 

`src/shared/components/TopcoderFooter/style.scss`

**Comment by r0hit-gupta** [comment]
@sushilshinde done

**Pull request merged**
