### PR TITLE
issue 2874 fix

### PR DESCRIPTION
**Pull request by PrakashDurlabhji**

### CODE REVIEW

**Comment by gurmeetb** [comment]
@PrakashDurlabhji can you fix the failing tests ?

**Comment by anonymousjaggu** [comment]
@PrakashDurlabhji please check MR it has conflicts

**Comment by anonymousjaggu** [comment]
@PrakashDurlabhji The existing behavior is broken, it is not going to filters by clicking tab

**Comment by PrakashDurlabhji** [comment]
@anonymousjaggu it was working well, it was in flow perfectly. I will check again.

**Comment by PrakashDurlabhji** [comment]
@anonymousjaggu it is working, can you please confirm once again? thanks

**Comment by anonymousjaggu** [comment]
@PrakashDurlabhji pressing tab should be the selection of the Sort By options, not the `Sort By` label you are highlighting now. please refer to the image 
image

**Comment by PrakashDurlabhji** [comment]
@anonymousjaggu closing it as not able to solve it

**Pull request closed without merging**
