### PR TITLE
Issue 2873 fix

### PR DESCRIPTION
**Pull request by PrakashDurlabhji**
Issue #2873

### CODE REVIEW

**Comment by codeMinter** [comment]
@PrakashDurlabhji we cannot change `eslintrc` - also resolve branch conflicts.

**Comment by PrakashDurlabhji** [comment]
@codeMinter means we cannot touch eslintrc at all?

**Comment by veshu** [comment]
@codeMinter ☝️

**Comment by codeMinter** [comment]
> @codeMinter means we cannot touch eslintrc at all?

Yes no changes to lint.

**Comment by codeMinter** [comment]
@PrakashDurlabhji Also do not remove `Code Failed` label unless you have updated PR.

**Comment by veshu** [comment]
@PrakashDurlabhji Please update on this as soon as early. Thanks!

**Comment by PrakashDurlabhji** [comment]
@codeMinter PR updated

**Comment by PrakashDurlabhji** [comment]
@codeMinter PR updated

**Pull request merged**
