### PR TITLE
issue 2903 fix

### PR DESCRIPTION
**Pull request by PrakashDurlabhji**
issue #2903

### CODE REVIEW

**Comment by gurmeetb** [comment]
@PrakashDurlabhji please make sure all your PR passes before picking next ticket. Looks like you rushed through a lot of issues, and all PRs I am seeing similar failing test cases. Please don't pick further tickets unless all your PR tests are resolved. 

@veshu FYI ☝️

**Comment by codeMinter** [comment]
@PrakashDurlabhji your change affects `Clear Filter` button also. 

ClearFilterButton

**Comment by PrakashDurlabhji** [comment]
@codeMinter  PR updated

**Comment by veshu** [comment]
@codeMinter Please check this. Thanks!

**Comment by codeMinter** [comment]
@PrakashDurlabhji please use `react-ui` variable in scss

**Comment by PrakashDurlabhji** [comment]
@veshu code updated.

**Comment by codeMinter** [comment]
@PrakashDurlabhji I was about to check your latest PR but I see they are not needed. I see button is already passing AA without your default settings. 👇 



@veshu ☝️

**Comment by PrakashDurlabhji** [comment]
@codeMinter my PR shall be merged because issues with contentful label are duplicated and PR against them are merged first then it is happening. I do not wish to lose efforts.

**Comment by codeMinter** [comment]
@veshu ☝️ these are unwanted changes, which I cannot approve for merging.

**Comment by PrakashDurlabhji** [comment]
@veshu will I be paid something atleast for efforts?

**Pull request closed without merging**
