### PR TITLE
MSFT-21-Issue#2744 - Changed background colors and text colors for better contrast ratio

### PR DESCRIPTION
**Pull request by romitgit**
Issue #2744

### CODE REVIEW

**Comment by codeMinter** [comment]
@romitgit please add colors in `react-ui` repo and reference variables here.

**Comment by romitgit** [comment]
@codeMinter fixed this in https://github.com/topcoder-platform/community-app/pull/2993/files#diff-8229575a721a845abf2b42d218a76b75

**Comment by codeMinter** [comment]
@romitgit if you mean you have 1 PR for 2 issues, then close PR and link the issue to other PR. We cannot merge this PR unless this PR is fixed.

**Comment by romitgit** [comment]
This is already fixed in https://github.com/topcoder-platform/community-app/pull/2993

Hence closing this PR

**Pull request closed without merging**
