### PR TITLE
issue 2696 fix

### PR DESCRIPTION
**Pull request by rashmi73**

### CODE REVIEW

**Comment by ThomasKranitsas** [comment]
Screenshot 2019-07-06 at 11 28 15

**Comment by ThomasKranitsas** [comment]
Finally displayed the data after making 210+ requests with an `offset` of 4700 🤔
Screenshot 2019-07-06 at 11 29 53

**Comment by rashmi73** [comment]
@ThomasKranitsas is it related to my changes?

I guess it should be present even before my PR.

kindly confirm.

**Comment by ThomasKranitsas** [comment]
Checking...

**Comment by sushilshinde** [comment]
@rashmi73 @ThomasKranitsas if it does exist before this PR please confirm on 

https://beta-community-app.topcoder.com/challenges

**Comment by rashmi73** [comment]
@sushilshinde yes checking

**Comment by sushilshinde** [comment]
@rashmi73 please update

**Comment by rashmi73** [comment]
@sushilshinde @ThomasKranitsas it is working fine on https://beta-community-app.topcoder.com/challenges

also locally on my machine my PR was behaving perfectly, 
I will test it once again on my local machine to confirm once again.
or else topcoder-react-lib, unnecesarily increasing offset on few combinations.

In an hour will update you.

**Comment by ThomasKranitsas** [comment]
@rashmi73 can I get an update, please? This is kinda urgent

**Comment by rashmi73** [comment]
@ThomasKranitsas sorry for late actively on this

**Comment by rashmi73** [comment]
@sushilshinde @ThomasKranitsas @nithyaasworld 
I analyzed complete scenario what happened in #2698  and what I did, and why offset goes till 4500 in my this PR.

this offset issue till 4500 is neither introduced by **mine or prakash PR** which is already merged.

1. In #2698 , Prakash raised PR to solve it, which removed code of @mhikeo , that PR was https://github.com/topcoder-platform/community-app/pull/2710/files which is merged, though it solved 2698 but broke other scenario. so before that PR was merged, mhikeo code already had this loading issue of offset=4500 present (but then mhikeo code also did not cover other scenario due to which combination of filters did not work), prakash PR removed that code and PR merged.

2. so now prakash code deployed on https://beta-community-app.topcoder.com, and there is no loading issue but one scenario failed.

3. now i took #2696 issue, i reverted what prakash did, so now i am on mhikeo code, which has loading issue, and to make all scenario work, i added mine minor code to handle all scenarios and mine current PR is raised .

4. so now https://beta-community-app.topcoder.com wont show loading offset=4500 issue, but mine PR will show loading offset issue because mhikeo code is also present as i modified and added few lines.

5. To verify my above claim, I removed mine modification and just ran whatever was present in mhikeo code(so now prakash code is not present) , so this loading offset=4500 is still present.

6. I also analyzed which offsett reaches 4500, and i feel it is due to code in topcoder-react-lib at https://github.com/topcoder-platform/topcoder-react-lib/blob/master/src/actions/challenge-listing.js#L52 not sure how much this affects, but surely problem is due to this file code as there is recursion in getAll function.

7.I could have surely handled this loading offset=4500 scenario but I am confused how this code flows.

I feel mine code should be merged to atleast satisfy the requirements of this combination of filters issue.

waiting for feedback

**Comment by ThomasKranitsas** [comment]
@sushilshinde the above report looks correct to me. I think we can merge this one and create a new ticket for the offset issue.

Thoughts?

**Pull request merged**
