### PR TITLE
Issue 2058 fixed

### PR DESCRIPTION
**Pull request by PrakashDurlabhji**

### CODE REVIEW

**Comment by ThomasKranitsas** [comment]
This does not fix the issue. There is still some delay before the toggle changes state. The toggles should not wait for the API response.

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas will this be ok?

**Comment by ThomasKranitsas** [comment]
The toggles should change state instantly when you click them

**Comment by ThomasKranitsas** [comment]
@PrakashDurlabhji can you please fix the tests?

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas yes sorry for delay

**Comment by ThomasKranitsas** [comment]
there are still errors 🤔

**Comment by ThomasKranitsas** [comment]
@PrakashDurlabhji if you are not planning to fix this, I'll open it again for pickup

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas apology for delay few minutes

**Comment by ThomasKranitsas** [comment]
@PrakashDurlabhji any update here?

**Comment by ThomasKranitsas** [comment]
oh, I see you opened it

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas already unassigned myself as could not solve it.

**Pull request closed without merging**
