### PR TITLE
Ticket #2161 - Fix user can upload oversize image to avatar

### PR DESCRIPTION
**Pull request by liqiang372**
If the user upload image more than 2MB, an error message will be shown

image

### CODE REVIEW

**Comment by ThomasKranitsas** [comment]
Please fix the failing tests

**Comment by ThomasKranitsas** [comment]
The error message is not visible on mobile.

**Comment by liqiang372** [comment]
@ThomasKranitsas I basically referenced how that is implemented in Hobbies page. And yes, Hobbies page also doesn't work. Do you think I should fix it in this pr or a different pr? is this already reported by others? if not, do you think I should fix all of them in this pr or a different pr

**Comment by ThomasKranitsas** [comment]
I'll open another ticket for mobile

**Pull request merged**
