### PR TITLE
[WIP] Upgrade node from 8.9.2 to 8.9.4 #646

### PR DESCRIPTION
**Pull request by arun1595**
- Upgrade node
- Upgrade the following dependencies:
  - eslint ^4.6.1  →  ^4.15.0 
  - eslint-import-resolver-babel-module ^4.0.0-beta.3  →   ^4.0.0 
  - eslint-plugin-import ^2.7.0  →   ^2.8.0 
  - eslint-plugin-jest ^21.0.2  →  ^21.6.2 
  - eslint-plugin-react  ^7.3.0  →   ^7.5.1
  - browser-cookies  ^1.1.0 → ^1.2.0
  - file-loader ^1.1.5  → ^1.1.6
  - style-loader ^0.19.0 → ^0.19.1
  - resolve-url-loader ^2.2.0 → ^2.2.1

### CODE REVIEW

**Comment by birdofpreyru** [comment]
I guess, *WIP* in the title means that this one is not ready for the review? Anyway, I've briefly checked, that there are much more deps to update:
image

**Comment by arun1595** [comment]
@birdofpreyru Yeah, it is not yet ready for review. I am slowly making progress with it and at the same time, don't want to give up.

**Comment by birdofpreyru** [comment]
Closing this PR for now, as I would like to finalize the Bug Bush, and this is still WIP.

**Comment by arun1595** [comment]
@birdofpreyru Got it, I'll try to make some progress this week, would love to get this done :smile:

**Pull request closed without merging**
