### PR TITLE
issue_1740 fixed

### PR DESCRIPTION
**Pull request by Gauravseta**

### CODE REVIEW

**Comment by ThomasKranitsas** [comment]
@Gauravseta I'm getting this:
screenshot 2018-11-23 at 13 46 39

**Comment by Gauravseta** [comment]
@ThomasKranitsas is failure page wokring properly?

**Comment by ThomasKranitsas** [comment]
The page is loading now but there seems to be a small styling issue. The main content background should be white, right?

screenshot 2018-11-23 at 15 04 06

This is for both success/failure.

Also, the `assets is not a function` is happening in `/settings/account/email-verification/expired`. Can you please fix it?
I'll bump up the price of the ticket if you can fix that within the next hour.

**Comment by Gauravseta** [comment]
@ThomasKranitsas yes i will fix it within half hr

**Comment by Gauravseta** [comment]
@ThomasKranitsas can you please check it? i updated as u said within 15 mins

**Pull request merged**
