### PR TITLE
MSFT-86

### PR DESCRIPTION
**Pull request by r0hit-gupta**
changes for #2797

### CODE REVIEW

**Comment by codeMinter** [comment]
@r0hit-gupta same `react-ui` issue

**Comment by r0hit-gupta** [comment]
@codeMinter done

**Comment by sushilshinde** [comment]
PR number `react-ui`?

**Comment by codeMinter** [comment]
@sushilshinde https://github.com/topcoder-platform/topcoder-react-ui-kit/pull/16

**Comment by r0hit-gupta** [comment]
@codeMinter @sushilshinde I have updated the PR as @Dara-K suggested in the issue. Color Palette has been updated at https://github.com/topcoder-platform/topcoder-react-ui-kit/pull/19

Please review. Thanks.

**Comment by sushilshinde** [comment]
https://github.com/topcoder-platform/topcoder-react-ui-kit/pull/19

Yet to release to so keeping this on hold

**Pull request merged**
