### PR TITLE
Issue #1208: Profile - Deleting an entry in the user traits should show the user consent popup

### PR DESCRIPTION
**Pull request by KevinLeigh**
Add user consent logic when deleting traits on following settings pages below:

**Profile**
Basic Info
Languages
Skills
Education
Work
Organization
Hobbies
Communities

**Tools**
Devices
Software
Service Providers
Subscriptions

**Account**
Linked Accounts

**Preferences**
E-mail

As well as simplify user consent logic to be more dynamic

### CODE REVIEW

**Comment by ThomasKranitsas** [comment]
@KevinLeigh did you just fix the hobbies?
All traits need to be fixed.

**Comment by KevinLeigh** [comment]
@ThomasKranitsas Hey there, yes I only did hobbies, sorry I misunderstood, I will update the rest when I am home. Please could you provide a list of all the places that consent form should be show?

**Comment by ThomasKranitsas** [comment]
Pretty much everything 🙂 

## Profile
- Basic Info
- Languages
- Skills
- Education
- Work
- Organization
- Hobbies
- Communities
 
## Tools
- Devices
- Software
- Service Providers
- Subscriptions
 
## Account
- Linked Accounts
 
## Preferences
- E-mail

**Comment by KevinLeigh** [comment]
@ThomasKranitsas Perfect, thank you for the update much appreciated. Will complete as soon as I am home :)

**Comment by ThomasKranitsas** [comment]
@KevinLeigh can you please give me an ETA on this?

**Comment by KevinLeigh** [comment]
@ThomasKranitsas Hey Thomas, sorry I have been really busy and just got home, will complete the rest of the issue after I have eaten and settled down. It should take me 2 - 3 hours to complete from when I start :).

**Comment by ThomasKranitsas** [comment]
Ok, sounds good. Thanks for the update

**Comment by KevinLeigh** [comment]
@ThomasKranitsas Anytime, going to start working on the consent form now :)

**Comment by KevinLeigh** [comment]
@ThomasKranitsas 

Hey Thomas.

I have added user consent logic to the rest of the pages :)

**Profile**
Basic Info
Languages
Skills
Education
Work
Organization
Hobbies
Communities

**Tools**
Devices
Software
Service Providers
Subscriptions

**Account**
Linked Accounts

**Preferences**
E-mail

All I need to do is `final testing` and `fix jslint errors`

**Comment by KevinLeigh** [comment]
@ThomasKranitsas I have completed final testing and fixed jslint errors (including 12 errors that existed since `new-develop`)

**Comment by ThomasKranitsas** [comment]
@KevinLeigh thanks! I'll test shortly

**Comment by ThomasKranitsas** [comment]
@KevinLeigh can you please resolve the merge conflicts? We've made a major update in the code to change the form layout.

**Comment by KevinLeigh** [comment]
@ThomasKranitsas Will do :)

**Comment by KevinLeigh** [comment]
@ThomasKranitsas Merge conflicts have been resolved

**Comment by KevinLeigh** [comment]
@ThomasKranitsas The jslint errors should be fixed now :).  Just a heads up, it is not advisable to use `eslint-disable` to disable jslint errors. Currently the project has 165 occurrences of `eslint-disable` across files, disabling lots of jslint in js/jsx files. I can do my best to remove as many jslint errors as possible on the project. If you would like me to, please create a ticket and assign to me. Much appreciated.

**Comment by KevinLeigh** [comment]
screen shot 2018-08-18 at 17 07 16

**Comment by KevinLeigh** [comment]
Thank you for the update, I will create a ticket a little shortly and notify @birdofpreyru if he would like to have changes made :)

**Comment by ThomasKranitsas** [comment]
@KevinLeigh We need some changes here.

1. Update the PR to be against `develop` and not `new-develop`.
2. We ONLY need to show the user consent popup if the `userConsent` property in the member's traits is `undefined`. We don't need to show it every time if the user has already picked an option.

I'll update the price of the ticket for the additional effort. 

Thanks!

**Comment by KevinLeigh** [comment]
@ThomasKranitsas Anytime, will make additional changes.

**Comment by KevinLeigh** [comment]
@ThomasKranitsas Will there be a userConsent field per trait ? Or is there one global userConsent field ?

**Comment by ThomasKranitsas** [comment]
I mean the one in the personalization trait object

**Comment by KevinLeigh** [comment]
@ThomasKranitsas I have made changes so that user consent modal will only show if userConsent field is undefined.

**Comment by ThomasKranitsas** [comment]
checking...

**Comment by KevinLeigh** [comment]
Thank you

**Comment by ThomasKranitsas** [comment]
@KevinLeigh this isn't really working for me. If the `userConsent` is present in the `personalization` trait, the page does not update any trait other than the basic info.

Video: http://take.ms/G35J5

**Comment by KevinLeigh** [comment]
@ThomasKranitsas Sorry about that, will have a look at it shortly and get back to you.

**Comment by KevinLeigh** [comment]
@ThomasKranitsas I found the problem and fixed it now. Changes are pushed, please could you re-test?

**Pull request merged**
