### PR TITLE
MSFT-18

### PR DESCRIPTION
**Pull request by r0hit-gupta**
changes for #2742

### CODE REVIEW

**Comment by codeMinter** [comment]
@veshu this is not right fix, we need fix in `react-ui` repo. So marking this as failed

**Comment by r0hit-gupta** [comment]
@codeMinter do you want me to create a variable in `react-ui` and then reference it here?

**Comment by r0hit-gupta** [comment]
@codeMinter done

**Comment by veshu** [comment]
@codeMinter @r0hit-gupta Is this fixed?

**Comment by codeMinter** [comment]
@veshu not yet, pending testing on myside. I am going by labels so removed Failed so I know I need to test this. Will flag once tested as Passed.

**Comment by veshu** [comment]
@r0hit-gupta Please confirm this if we need this PR is needed or w.r.t. https://github.com/topcoder-platform/topcoder-react-ui-kit/pull/19

@asadath1395 Please review this.

**Comment by r0hit-gupta** [comment]
@veshu this PR is still needed.

**Pull request merged**
