### PR TITLE
Issue 3231 fix

### PR DESCRIPTION
**Pull request by rashmi73**

### CODE REVIEW

**Comment by r0hit-gupta** [comment]
@rashmi73 the tests are failing. Please fix.

**Comment by veshu** [comment]
@r0hit-gupta Please check this. Thanks!

**Comment by r0hit-gupta** [comment]
@rashmi73 this is not the intended fix. After focusing on the date input, `tab` key needs to be pressed again to focus on the calendar, after which everything works fine including the `?` key. Try to find a fix which directly puts the calendar into focus without an additional `tab` press. Please let me know if something is still not clear. Thanks!

**Comment by rashmi73** [comment]
@r0hit-gupta did my solution change the behaviour of existing working functionality?
I guess it was already working like that, and requirement of the issue was to make "?" work, which I guess is already working fine.Still I will confirm whether such behaviour is introduced due to me or is it just an enhancement you are talking about.

@veshu

**Comment by r0hit-gupta** [comment]
@rashmi73 in short, we need to make the `?` key work without having to press the `tab` key twice. The `?` key should work as soon as the date input is focused. I hope that clears it up. 
@veshu please provide additional inputs, if any. Thanks!

**Comment by rashmi73** [comment]
@r0hit-gupta surely I will give a try but that becomes a enhancement as it may require current behaviour modification completely which I do not feel is scope.

@veshu I am trying it and I will do it.

**Comment by veshu** [comment]
> @veshu I am trying it and I will do it

Ok thanks!

**Comment by rashmi73** [comment]
@veshu @r0hit-gupta kindly verify taking my PR and make sure 

1.from node_modules react-dates is deleted
2. run 'npm install'

go to firefox and try focus on calendar using tab, then press "?" however possible on your keyboard, shortcuts will open, 

no need to press tab twice to enter calendar.

kindly confirm

**Comment by veshu** [comment]
@r0hit-gupta please verify if this works, thanks!

**Pull request merged**
