### PR TITLE
Issue #1163: Profile - Fix flickering issue on the basic info page

### PR DESCRIPTION
**Pull request by KevinLeigh**
### Description

Please see issue description [here](https://github.com/topcoder-platform/community-app/issues/1163)

### Changes

- Extend React.PureComponent 
- Remove dispatch calls to non existing redux actions

### CODE REVIEW

**Comment by ThomasKranitsas** [comment]
@KevinLeigh your changes introduced few issues:
- [ ] The performance has been significantly dropped when switching sub-pages (eg from Profile to Tools).
- [ ] If I go to `Profile > Education` then go to `Tools` then go back to `Profile > Basic info`, the form is empty (data is missing).

Can you please fix the issues above and make sure your changes don't break any of the existing functionality?

**Comment by KevinLeigh** [comment]
@ThomasKranitsas Hey there, nice catch. I did not expect there to be those issues with changes as there is fundamentally no business logic changes, I did find the issue and fixed it.

The issue was due to changing profile related components to extend React.PureComponent instead of React.Component.

**Comment by ThomasKranitsas** [comment]
Ok, I'll check and I'll let you know. Thanks a lot for the quick fix

**Comment by ThomasKranitsas** [comment]
The performance issue hasn't been fixed but I think that could be a separate ticket. Could you please follow up on the new ticket to resolve the performance issue?

**Comment by KevinLeigh** [comment]
@ThomasKranitsas 

It seems to be slower on new-develop, I just profiled the performance.

- Page load for `new-develop`:

screen shot 2018-08-14 at 19 23 51

- Change tab for `new-develop`:

screen shot 2018-08-14 at 19 24 19

- Page load for `issue-1163-profile-flickering`:

screen shot 2018-08-14 at 19 21 06

- Change tab for `issue-1163-profile-flickering`:

screen shot 2018-08-14 at 19 22 34

Summary of performance seen in screenshots above:

1) Page load on this branch is 515 ms faster on this branch than `new-develop`
2) Changing tabs is roughly 450 - 500 ms faster on this branch than `new-develop`

**Comment by KevinLeigh** [comment]
@ThomasKranitsas Could I please rather work off a new issue improving profile screen performance off of `new-develop` branch ?

**Comment by ThomasKranitsas** [comment]
Indeed, the performance issue was not caused by your changes. I'll revert the price to the original and i'll create a new ticket for the performance issue.

**Comment by ThomasKranitsas** [comment]
@KevinLeigh fyi https://github.com/topcoder-platform/community-app/issues/1173

**Comment by KevinLeigh** [comment]
@ThomasKranitsas Thank you Thomas, much appreciated, please could you assign new ticket to me ?

**Pull request merged**
