### PR TITLE
Fix Server-side filtering on challenge listings

### PR DESCRIPTION
**Pull request by nauhil**
@ThomasKranitsas Please review it

FYI 
1. I found that the metadata of challenges from backend response is not stable, demo video https://monosnap.com/file/trhOWwV9OM4ze0z3YnbsVVXtbfOJLe

2. I've update code for Re-calculate metadata of challenges after fetch challenges, demo video https://monosnap.com/file/3leK5abCP8YTPrfOBCrtsJQC8YVDIl

### CODE REVIEW

**Comment by ThomasKranitsas** [comment]
@nauhil can you please fix the failing tests?

**Comment by ThomasKranitsas** [comment]
@nauhil can you please fix the failing tests?

**Comment by nauhil** [comment]
Have been fixed and committed yesterday

Still failing?

**Comment by ThomasKranitsas** [comment]
Yes, take a look here https://circleci.com/gh/topcoder-platform/community-app/4485

**Comment by nauhil** [comment]
it seems community-app does not reference latest topcoder-react-lib, so tests failed

**Comment by ThomasKranitsas** [comment]
ah, yes, that could be it. Let me update the react lib and trigger the tests again.

**Pull request merged**
