### PR TITLE
changing gender type prefer not to answer issue_1107 fixed

### PR DESCRIPTION
**Pull request by PrakashDurlabhji**

### CODE REVIEW

**Comment by ThomasKranitsas** [comment]
@PrakashDurlabhji you also need to capitalize the other options.
`male` should become `Male` and `female` should become `Female`.

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas ok sorry forgot that , but i feel, it will capitalize the first letter due to css property, which is present.

**Comment by ThomasKranitsas** [comment]
Yes but the data in the API call will have the options in lowercase which will throw an 400 BAD REQUEST ;)

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas just 1 min i will commit it.

**Pull request merged**
