### PR TITLE
MSFT 222 issue#2881 - Fixed color contrast issues

### PR DESCRIPTION
**Pull request by romitgit**

### CODE REVIEW

**Comment by romitgit** [comment]
Fixes following two issues:

https://github.com/topcoder-platform/community-app/issues/2744
https://github.com/topcoder-platform/community-app/issues/2881

**Comment by veshu** [comment]
@romitgit Is it possible to separate out the PR per issues?

Or this single fix for both issue?

**Comment by codeMinter** [comment]
@romitgit We will need single PR per ticket. We cannot accept single PR for 2 issues. Kindly fix and raise separate PR for each ticket.

**Comment by romitgit** [comment]
Fixes https://github.com/topcoder-platform/community-app/issues/2881

Dependent PR
PR for topcoder-react-ui-kit : https://github.com/topcoder-platform/topcoder-react-ui-kit/pull/15

**Comment by romitgit** [comment]
@codeMinter Separated out the PRs. Please review now

**Comment by codeMinter** [comment]
@romitgit We don't need changes for `src/shared/utils/tc.js` -  without it I see all passed AA, can you update PR?

**Comment by romitgit** [comment]
@codeMinter Updated the PR. Please review. Thanks.

**Pull request merged**
