### PR TITLE
issue_1643 fix

### PR DESCRIPTION
**Pull request by PrakashDurlabhji**

### CODE REVIEW

**Comment by ThomasKranitsas** [comment]
@PrakashDurlabhji you need to run `npm run jest -- -u` to update the snapshots. Can you please do that so I can merge this PR?

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas I am just confusd what to be done.
so now i need to run the above command and make a commit again?

**Comment by ThomasKranitsas** [comment]
Yes, if you run the command I posted above, it'll update the existing snapshots and you'll just have to commit the changes.

**Comment by ThomasKranitsas** [comment]
Something went terribly wrong here 🤔 Let me check it... Don't push anything. I'll fix the tests

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas ok. also kindly tell me what is to be done exactly as everytime i dont wana see this issue repeat and solve it myself if it occurs.

**Comment by ThomasKranitsas** [comment]
How I fixed it was:

- `git reset HEAD~` to undo your last commit
- `nvm use` to use the correct versions of node/npm
- `npm i` to install the dependencies
- `npm run build` to build the app
- `npm run jest -- -u` to run the jest tests and update the snapshots

**Pull request merged**
