### PR TITLE
Issue 1643 fixed

### PR DESCRIPTION
**Pull request by PrakashDurlabhji**

### CODE REVIEW

**Comment by ThomasKranitsas** [comment]
Can you please fix the failing tests?

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas yes fixing it immediatly

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas i doubt its due to mine because,
its in file:
home/circleci/project/src/shared/components/SubmissionPage/Submit/index.jsx

there are no changes made by me in this file. still i will take a look to remove it.

**Comment by ThomasKranitsas** [comment]
Thanks!

**Comment by ThomasKranitsas** [comment]
I guess you should also run `npm run jest -- -u` to fix the snapshot tests

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas running that command

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas i ran that command what to do now? i dont see any file changes in any files except these kind of files:

     modified:   __tests__/shared/components/Leaderboard/__snapshots__/PodiumSpot.jsx.snap

**Comment by gurmeetb** [comment]
@PrakashDurlabhji compare `home/circleci/project/src/shared/components/SubmissionPage/Submit/index.jsx` with develop - I have already fixed in my MR - I saw similar issue with this file as yours. Just merge with develop and you should be good with the lint issue for `home/circleci/project/src/shared/components/SubmissionPage/Submit/index.jsx`

**Comment by ThomasKranitsas** [comment]
@PrakashDurlabhji ☝️

**Comment by ThomasKranitsas** [comment]
Any update on this one?

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas sure.update u within 10mins.

**Comment by PrakashDurlabhji** [comment]
@ThomasKranitsas raised a new PR.hence closing this one

**Comment by PrakashDurlabhji** [comment]
@gurmeetb thanks for help

**Pull request closed without merging**
