### PR TITLE
Fix for Issue #2832 - Deadlines section

### PR DESCRIPTION
**Pull request by gets0ul**
#2832 
MSFT-136 Read deadlines section

### CODE REVIEW

**Comment by sushilshinde** [comment]
@gets0ul tests are failing

**Comment by asadath1395** [comment]
@sushilshinde I had checked in my local, every tests had passed

**Comment by gets0ul** [comment]
Will create new PR because the previous one is done before those lint errors are fixed.

**Comment by gets0ul** [comment]
New PR is here: https://github.com/topcoder-platform/community-app/pull/3121

**Comment by sushilshinde** [comment]
@gets0ul thanks will wait for review

**Pull request closed without merging**
