### PR TITLE
convert to pwa

### PR DESCRIPTION
**Pull request by liuliquan**

### CODE REVIEW

**Comment by sushilshinde** [comment]
I'll test the whole thing tomorrow.

**Comment by liuliquan** [comment]
I think I made a wrong assumption that the service worker could be served from CDN with different domain. It looks like it has to be from the same origin domain.

E.g. When deployed in prod, it needs be from "https://www.topcoder.com/sw.js" or "https://community-app.topcoder.com/sw.js", but not from the cloudfront.net CDN

Then what would be the preferred path of the service worker?

**Comment by liuliquan** [comment]
The reference: https://github.com/w3c/ServiceWorker/issues/940

**Comment by ThomasKranitsas** [comment]
@sushilshinde ☝️

**Comment by sushilshinde** [comment]
@liuliquan @ThomasKranitsas 

Path should be `https://www.topcoder.com/challenges`

**Comment by liuliquan** [comment]
Done. The service worker path is at `/challenges/sw.js`.

And it needs be accessible from `https://www.topcoder.com/challenges/sw.js` and `https://community-app.topcoder.com/challenges/sw.js` when deployed in prod.

**Pull request merged**
