### PR TITLE
Disabled Verification btn

### PR DESCRIPTION
**Pull request by akmarif**
Disabled Verification button when email is empty

screen shot 2018-10-20 at 10 05 38 am

### CODE REVIEW

**Comment by akmarif** [comment]
fixing the tests

**Comment by akmarif** [comment]
tests are fixed!

**Comment by ThomasKranitsas** [comment]
This is not the expected fix.

The issue is that when you enter the new password, the validation popup prevents the user from clicking the change password button http://take.ms/V4e4W so the user has to click outside of the input to hide the popup and then click change password.

**Comment by akmarif** [comment]
fixing it

**Comment by akmarif** [comment]
@ThomasKranitsas are you talking about this issue https://github.com/topcoder-platform/community-app/issues/1438 ?
I found no concern regarding password at issue description.

**Comment by ThomasKranitsas** [comment]
My bad! I thought this was related to another ticket

**Comment by akmarif** [comment]
@ThomasKranitsas can you please review this PR?

**Comment by akmarif** [comment]
@ThomasKranitsas can you please review this PR?

**Pull request merged**
