### PR TITLE
issue 2406 fixed

### PR DESCRIPTION
**Pull request by PrakashDurlabhji**

### CODE REVIEW

**Comment by luizrrodrigues** [comment]
@PrakashDurlabhji ☝️

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues yes

**Comment by luizrrodrigues** [comment]
@PrakashDurlabhji Any status on fixes?

**Comment by PrakashDurlabhji** [comment]
@luizrrodrigues it is working well now. PR updated

**Comment by sushilshinde** [comment]
@luizrrodrigues what to do with this?

**Comment by luizrrodrigues** [comment]
@sushilshinde Sorry I miss to close this one.

**Pull request closed without merging**
