### PR TITLE
Issue 2892 fix

### PR DESCRIPTION
**Pull request by PrakashDurlabhji**

### CODE REVIEW

**Comment by anonymousjaggu** [comment]
@PrakashDurlabhji it's still not fixed in Edge browser

**Comment by PrakashDurlabhji** [comment]
@anonymousjaggu PR updated

**Comment by anonymousjaggu** [comment]
@PrakashDurlabhji Please check the video https://drive.google.com/file/d/1xKtLZ6wTMbyO8U7-yyvYwPXwVaH58KAT/view?usp=sharing

Your fix still not working, next time please share short verification video as well so it will be easier for me. and please make sure issue is in `Edge` browser

**Comment by PrakashDurlabhji** [comment]
@anonymousjaggu sorry for it, surely i will paste video now.

**Comment by PrakashDurlabhji** [comment]
@anonymousjaggu can you please try once again because suddenly edge showing some issues, behaving weird. 
Please try once again it will work now.

**Comment by anonymousjaggu** [comment]
@PrakashDurlabhji if the fix is working on your side as I had asked you to provide video
It's still not working

**Comment by PrakashDurlabhji** [comment]
@anonymousjaggu pasting video in sometime it is recorded but suddenly there is power cut due to heavy rain, hence will update in few time, and also update tests so it doesnt break.

**Comment by PrakashDurlabhji** [comment]
@anonymousjaggu here is verification video

[issue2892.zip](https://github.com/topcoder-platform/community-app/files/3437950/issue2892.zip)

**Comment by veshu** [comment]
@anonymousjaggu PR is updated, please review this.

**Comment by veshu** [comment]
@anonymousjaggu Any update here please?

**Comment by anonymousjaggu** [comment]
reviewing it

**Comment by anonymousjaggu** [comment]
`MR` looks fine now

**Pull request merged**
