### PR TITLE
fix for issue #2661

### PR DESCRIPTION
**Pull request by gurmeetb**
fix for issue #2661

### CODE REVIEW

**Comment by ThomasKranitsas** [comment]
@gurmeetb I've changed the base to `server_side_filtering_fixes`. This is the branch we should use for this. Sorry for the confusion. Can you please fix the tests?

**Comment by gurmeetb** [comment]
@ThomasKranitsas tests are already fixed on `server_side_filtering_fixes` - is there a way we could run them again ?

**Comment by gurmeetb** [comment]
wait let me close this PR and create a new one which should trigger them again and try.

**Comment by gurmeetb** [comment]
@ThomasKranitsas we are all good here now

**Pull request merged**
