### PR TITLE
MSFT-99

### PR DESCRIPTION
**Pull request by r0hit-gupta**
changes for #2804

### CODE REVIEW

**Comment by codeMinter** [comment]
@r0hit-gupta this just keep reading `Blank`, the requirement is to read `filter button`.

**Comment by codeMinter** [comment]
also resolve conflicts plz

**Comment by codeMinter** [comment]
@r0hit-gupta if you are blocked, we will need to open this. I will wait for updated PR for next 4 hrs, after which I will need to open this for others.

**Comment by r0hit-gupta** [comment]
@codeMinter working on it.

**Comment by r0hit-gupta** [comment]
@codeMinter the fix is working fine for me. Are you using JAWS?

**Comment by codeMinter** [comment]
@r0hit-gupta with your last commit, I don't see any changes for files?

**Comment by r0hit-gupta** [comment]
> @codeMinter the fix is working fine for me. Are you using JAWS?

@codeMinter the commit was to resolve merge conflicts. Can you please let me know which screen reader are you using?

**Comment by veshu** [comment]
@codeMinter Please check the updated PR. Thanks!

**Comment by codeMinter** [comment]
@veshu there are no changes in PR, looks like this is fixed issue in repo already. Hence, closing PR. Please take it ahead for QA verification.

**Pull request closed without merging**
