### PR TITLE
issue_1660 fixed

### PR DESCRIPTION
**Pull request by Gauravseta**

### CODE REVIEW

**Comment by ThomasKranitsas** [comment]
there are some failing tests

**Comment by ThomasKranitsas** [comment]
I'm getting `Error: Cannot find module 'react-dates/initialize'`

**Comment by ThomasKranitsas** [comment]
Any update?
@Gauravseta

**Comment by Gauravseta** [comment]
@ThomasKranitsas apology for delay will see it immediately. it was working well on my machine though. will see if version mismatch

**Comment by ThomasKranitsas** [comment]
Can you please prioritize this one?

**Comment by Gauravseta** [comment]
@ThomasKranitsas yes sure. just few hours.

**Comment by ThomasKranitsas** [comment]
Can I have an update on this please?

**Comment by ThomasKranitsas** [comment]
can you please fix the tests?

**Comment by ThomasKranitsas** [comment]
This is not working correctly.

The layout looks broken and I'm getting a lot of issues in the console log.

screenshot 2018-11-23 at 14 01 00

**Comment by Gauravseta** [comment]
@ThomasKranitsas dont know why behaving like this. looking into it.

**Comment by ThomasKranitsas** [comment]
@Gauravseta it's been a long time since you picked that ticket. If you don't fix it in the next 2 hours, I'll open the ticket for pickup.

**Comment by Gauravseta** [comment]
@ThomasKranitsas apology for delay. but ui seems to be confusing and getting year is a major task. i feel its difficult.i will make it open as i wont be able to complete.

**Pull request closed without merging**
