### PR TITLE
[$10] - LoadingIndicator triggers warnings about incorrect SSR #603

### PR DESCRIPTION
**Pull request by ekundayo-ab**
### What does this PR do?
This pull request ensures a default prop is set with a default property to suppress the trigger warnings about incorrect server side rendering.

### Description of Task to be completed?
According to the react documentation on this warnings [here](https://reactjs.org/docs/dom-elements.html#suppresshydrationwarning) Set `suppressHydrationWarning: true` on the element

### How should this be manually tested?
1. Pull in latest changes from remote repository to local repository
2. Fire up terminal run `npm install`
3. Run `npm run dev` to start up application in development environment
4. Visit url supplied by the application usually **http://localhost:3000**, navigate to login page
5. login with `username: dan_developer` and `password: dantopcoder123` for normal user access
6. Try to reproduce warnings as described here #603

### Any background context you want to provide?
N/A

### What are the relevant issues tracker number?
[$10] - LoadingIndicator triggers warnings about incorrect SSR #603

### Screenshots (if appropriate)
N/A

### Questions:
N/A

### CODE REVIEW

**Comment by ekundayo-ab** [comment]
#709

**Comment by birdofpreyru** [comment]
@ekundayo-ab 
This does not work: run the app locally in dev mode, then go to http://local.topcoder-dev.com:3000/examples/loading-indicators with open dev console in browser. You'll still see the warning like this one:
```
Warning: Prop `dangerouslySetInnerHTML` did not match.
Server: "<div class=\"src-shared-components-examples-LoadingIndicators-style___page\" data-reactroot=\"\"><h1>Loading Indicators</h1><p>Demo of loading indicators we have in the code base. At the moment we have just one type, but you can flexibly tune its size / coloring using SCSS:</p><div class=\"src-shared-components-examples-LoadingIndicators-style___white-bg\"><svg class=\"src-shared-components-examples-LoadingIndicators-style___indicatorContainer src-shared-components-LoadingIndicator-styles___container\" viewBox=\"0 0 64 64\"><circle class=\"src-shared-components-LoadingIndicator-styles___circle1\" cx=\"32\" cy=\"32\" r=\"22.266432223293062\" id=\"loading-indicator-circle1\" opacity=\"0.700260722258883\"></circle><circle class=\"src-shared-components-LoadingIndicator-styles___circle2\" cx=\"32\" cy=\"32\" r=\"2.5959982233152323\" id=\"loading-indicator-circle2\" opacity=\"0.9977452222596748\"></circle></svg><svg class=\"src-shared-components-examples-LoadingIndicators-green-red-theme___container src-shared-components-LoadingIndicator-styles___container\" viewBox=\"0 0 64 64\"><circle class=\"src-shared-components-examples-LoadingIndicators-green-red-theme___circle1 src-shared-components-LoadingIndicator-styles___circle1\" cx=\"32\" cy=\"32\" r=\"22.266432223293062\" id=\"loading-indicator-circle1\" opacity=\"0.700260722258883\"></circle><circle class=\"src-shared-components-examples-LoadingIndicators-green-red-theme___circle2 src-shared-components-LoadingIndicator-styles___circle2\" cx=\"32\" cy=\"32\" r=\"2.5959982233152323\" id=\"loading-indicator-circle2\" opacity=\"0.9977452222596748\"></circle></svg><svg class=\"src-shared-components-examples-LoadingIndicators-yellow-pink-theme___container src-shared-components-LoadingIndicator-styles___container\" viewBox=\"0 0 64 64\"><circle class=\"src-shared-components-examples-LoadingIndicators-yellow-pink-theme___circle1 src-shared-components-LoadingIndicator-styles___circle1\" cx=\"32\" cy=\"32\" r=\"22.266432223293062\" id=\"loading-indicator-circle1\" opacity=\"0.700260722258883\"></circle><circle class=\"src-shared-components-examples-LoadingIndicators-yellow-pink-theme___circle2 src-shared-components-LoadingIndicator-styles___circle2\" cx=\"32\" cy=\"32\" r=\"2.5959982233152323\" id=\"loading-indicator-circle2\" opacity=\"0.9977452222596748\"></circle></svg></div><div class=\"src-shared-components-examples-LoadingIndicators-style___black-bg\"><svg class=\"src-shared-components-examples-LoadingIndicators-style___indicatorContainer src-shared-components-LoadingIndicator-styles___container\" viewBox=\"0 0 64 64\"><circle class=\"src-shared-components-LoadingIndicator-styles___circle1\" cx=\"32\" cy=\"32\" r=\"22.266432223293062\" id=\"loading-indicator-circle1\" opacity=\"0.700260722258883\"></circle><circle class=\"src-shared-components-LoadingIndicator-styles___circle2\" cx=\"32\" cy=\"32\" r=\"2.5959982233152323\" id=\"loading-indicator-circle2\" opacity=\"0.9977452222596748\"></circle></svg><svg class=\"src-shared-components-examples-LoadingIndicators-green-red-theme___container src-shared-components-LoadingIndicator-styles___container\" viewBox=\"0 0 64 64\"><circle class=\"src-shared-components-examples-LoadingIndicators-green-red-theme___circle1 src-shared-components-LoadingIndicator-styles___circle1\" cx=\"32\" cy=\"32\" r=\"22.266432223293062\" id=\"loading-indicator-circle1\" opacity=\"0.700260722258883\"></circle><circle class=\"src-shared-components-examples-LoadingIndicators-green-red-theme___circle2 src-shared-components-LoadingIndicator-styles___circle2\" cx=\"32\" cy=\"32\" r=\"2.5959982233152323\" id=\"loading-indicator-circle2\" opacity=\"0.9977452222596748\"></circle></svg><svg class=\"src-shared-components-examples-LoadingIndicators-yellow-pink-theme___container src-shared-components-LoadingIndicator-styles___container\" viewBox=\"0 0 64 64\"><circle class=\"src-shared-components-examples-LoadingIndicators-yellow-pink-theme___circle1 src-shared-components-LoadingIndicator-styles___circle1\" cx=\"32\" cy=\"32\" r=\"22.266432223293062\" id=\"loading-indicator-circle1\" opacity=\"0.700260722258883\"></circle><circle class=\"src-shared-components-examples-LoadingIndicators-yellow-pink-theme___circle2 src-shared-components-LoadingIndicator-styles___circle2\" cx=\"32\" cy=\"32\" r=\"2.5959982233152323\" id=\"loading-indicator-circle2\" opacity=\"0.9977452222596748\"></circle></svg></div><div class=\"src-shared-components-examples-LoadingIndicators-style___striped-bg\"><svg class=\"src-shared-components-examples-LoadingIndicators-style___indicatorContainer src-shared-components-LoadingIndicator-styles___container\" viewBox=\"0 0 64 64\"><circle class=\"src-shared-components-LoadingIndicator-styles___circle1\" cx=\"32\" cy=\"32\" r=\"22.266432223293062\" id=\"loading-indicator-circle1\" opacity=\"0.700260722258883\"></circle><circle class=\"src-shared-components-LoadingIndicator-styles___circle2\" cx=\"32\" cy=\"32\" r=\"2.5959982233152323\" id=\"loading-indicator-circle2\" opacity=\"0.9977452222596748\"></circle></svg><svg class=\"src-shared-components-examples-LoadingIndicators-green-red-theme___container src-shared-components-LoadingIndicator-styles___container\" viewBox=\"0 0 64 64\"><circle class=\"src-shared-components-examples-LoadingIndicators-green-red-theme___circle1 src-shared-components-LoadingIndicator-styles___circle1\" cx=\"32\" cy=\"32\" r=\"22.266432223293062\" id=\"loading-indicator-circle1\" opacity=\"0.700260722258883\"></circle><circle class=\"src-shared-components-examples-LoadingIndicators-green-red-theme___circle2 src-shared-components-LoadingIndicator-styles___circle2\" cx=\"32\" cy=\"32\" r=\"2.5959982233152323\" id=\"loading-indicator-circle2\" opacity=\"0.9977452222596748\"></circle></svg><svg class=\"src-shared-components-examples-LoadingIndicators-yellow-pink-theme___container src-shared-components-LoadingIndicator-styles___container\" viewBox=\"0 0 64 64\"><circle class=\"src-shared-components-examples-LoadingIndicators-yellow-pink-theme___circle1 src-shared-components-LoadingIndicator-styles___circle1\" cx=\"32\" cy=\"32\" r=\"22.266432223293062\" id=\"loading-indicator-circle1\" opacity=\"0.700260722258883\"></circle><circle class=\"src-shared-components-examples-LoadingIndicators-yellow-pink-theme___circle2 src-shared-components-LoadingIndicator-styles___circle2\" cx=\"32\" cy=\"32\" r=\"2.5959982233152323\" id=\"loading-indicator-circle2\" opacity=\"0.9977452222596748\"></circle></svg></div></div>"
Client: "<div class=\"src-shared-components-examples-LoadingIndicators-style___page\" data-reactroot=\"\"><h1>Loading Indicators</h1><p>Demo of loading indicators we have in the code base. At the moment we have just one type, but you can flexibly tune its size / coloring using SCSS:</p><div class=\"src-shared-components-examples-LoadingIndicators-style___white-bg\"><svg class=\"src-shared-components-examples-LoadingIndicators-style___indicatorContainer src-shared-components-LoadingIndicator-styles___container\" viewBox=\"0 0 64 64\"><circle class=\"src-shared-components-LoadingIndicator-styles___circle1\" cx=\"32\" cy=\"32\" r=\"28\" id=\"loading-indicator-circle1\"></circle><circle class=\"src-shared-components-LoadingIndicator-styles___circle2\" cx=\"32\" cy=\"32\" r=\"6\" id=\"loading-indicator-circle2\"></circle></svg><svg class=\"src-shared-components-examples-LoadingIndicators-green-red-theme___container src-shared-components-LoadingIndicator-styles___container\" viewBox=\"0 0 64 64\"><circle class=\"src-shared-components-examples-LoadingIndicators-green-red-theme___circle1 src-shared-components-LoadingIndicator-styles___circle1\" cx=\"32\" cy=\"32\" r=\"28\" id=\"loading-indicator-circle1\"></circle><circle class=\"src-shared-components-examples-LoadingIndicators-green-red-theme___circle2 src-shared-components-LoadingIndicator-styles___circle2\" cx=\"32\" cy=\"32\" r=\"6\" id=\"loading-indicator-circle2\"></circle></svg><svg class=\"src-shared-components-examples-LoadingIndicators-yellow-pink-theme___container src-shared-components-LoadingIndicator-styles___container\" viewBox=\"0 0 64 64\"><circle class=\"src-shared-components-examples-LoadingIndicators-yellow-pink-theme___circle1 src-shared-components-LoadingIndicator-styles___circle1\" cx=\"32\" cy=\"32\" r=\"28\" id=\"loading-indicator-circle1\"></circle><circle class=\"src-shared-components-examples-LoadingIndicators-yellow-pink-theme___circle2 src-shared-components-LoadingIndicator-styles___circle2\" cx=\"32\" cy=\"32\" r=\"6\" id=\"loading-indicator-circle2\"></circle></svg></div><div class=\"src-shared-components-examples-LoadingIndicators-style___black-bg\"><svg class=\"src-shared-components-examples-LoadingIndicators-style___indicatorContainer src-shared-components-LoadingIndicator-styles___container\" viewBox=\"0 0 64 64\"><circle class=\"src-shared-components-LoadingIndicator-styles___circle1\" cx=\"32\" cy=\"32\" r=\"28\" id=\"loading-indicator-circle1\"></circle><circle class=\"src-shared-components-LoadingIndicator-styles___circle2\" cx=\"32\" cy=\"32\" r=\"6\" id=\"loading-indicator-circle2\"></circle></svg><svg class=\"src-shared-components-examples-LoadingIndicators-green-red-theme___container src-shared-components-LoadingIndicator-styles___container\" viewBox=\"0 0 64 64\"><circle class=\"src-shared-components-examples-LoadingIndicators-green-red-theme___circle1 src-shared-components-LoadingIndicator-styles___circle1\" cx=\"32\" cy=\"32\" r=\"28\" id=\"loading-indicator-circle1\"></circle><circle class=\"src-shared-components-examples-LoadingIndicators-green-red-theme___circle2 src-shared-components-LoadingIndicator-styles___circle2\" cx=\"32\" cy=\"32\" r=\"6\" id=\"loading-indicator-circle2\"></circle></svg><svg class=\"src-shared-components-examples-LoadingIndicators-yellow-pink-theme___container src-shared-components-LoadingIndicator-styles___container\" viewBox=\"0 0 64 64\"><circle class=\"src-shared-components-examples-LoadingIndicators-yellow-pink-theme___circle1 src-shared-components-LoadingIndicator-styles___circle1\" cx=\"32\" cy=\"32\" r=\"28\" id=\"loading-indicator-circle1\"></circle><circle class=\"src-shared-components-examples-LoadingIndicators-yellow-pink-theme___circle2 src-shared-components-LoadingIndicator-styles___circle2\" cx=\"32\" cy=\"32\" r=\"6\" id=\"loading-indicator-circle2\"></circle></svg></div><div class=\"src-shared-components-examples-LoadingIndicators-style___striped-bg\"><svg class=\"src-shared-components-examples-LoadingIndicators-style___indicatorContainer src-shared-components-LoadingIndicator-styles___container\" viewBox=\"0 0 64 64\"><circle class=\"src-shared-components-LoadingIndicator-styles___circle1\" cx=\"32\" cy=\"32\" r=\"28\" id=\"loading-indicator-circle1\"></circle><circle class=\"src-shared-components-LoadingIndicator-styles___circle2\" cx=\"32\" cy=\"32\" r=\"6\" id=\"loading-indicator-circle2\"></circle></svg><svg class=\"src-shared-components-examples-LoadingIndicators-green-red-theme___container src-shared-components-LoadingIndicator-styles___container\" viewBox=\"0 0 64 64\"><circle class=\"src-shared-components-examples-LoadingIndicators-green-red-theme___circle1 src-shared-components-LoadingIndicator-styles___circle1\" cx=\"32\" cy=\"32\" r=\"28\" id=\"loading-indicator-circle1\"></circle><circle class=\"src-shared-components-examples-LoadingIndicators-green-red-theme___circle2 src-shared-components-LoadingIndicator-styles___circle2\" cx=\"32\" cy=\"32\" r=\"6\" id=\"loading-indicator-circle2\"></circle></svg><svg class=\"src-shared-components-examples-LoadingIndicators-yellow-pink-theme___container src-shared-components-LoadingIndicator-styles___container\" viewBox=\"0 0 64 64\"><circle class=\"src-shared-components-examples-LoadingIndicators-yellow-pink-theme___circle1 src-shared-components-LoadingIndicator-styles___circle1\" cx=\"32\" cy=\"32\" r=\"28\" id=\"loading-indicator-circle1\"></circle><circle class=\"src-shared-components-examples-LoadingIndicators-yellow-pink-theme___circle2 src-shared-components-LoadingIndicator-styles___circle2\" cx=\"32\" cy=\"32\" r=\"6\" id=\"loading-indicator-circle2\"></circle></svg></div></div>"
```
You can verify that markup generated at the server side is different from the client markup at the moment  the app loading only by params of the loading indicators, that start to be animated before the main bundle is loaded.

**Comment by ekundayo-ab** [comment]
Hi @birdofpreyru can't seem to reproduce this issue again, does it occur in the `develop` branch also?

**Comment by birdofpreyru** [comment]
Yes, it happens in *develop* branch, both before and after I have applied your PR. Do you run the app locally with `npm run dev` command?

**Pull request closed without merging**
