### PR TITLE
issue 2835 fix

### PR DESCRIPTION
**Pull request by PrakashDurlabhji**

### CODE REVIEW

**Comment by anonymousjaggu** [comment]
Hi @PrakashDurlabhji 
This is still reading as a link, you must add `aria-label` in parent anchor tag instead of span

**Comment by PrakashDurlabhji** [comment]
@anonymousjaggu added a tag instead of span, test case may fail, I will update it, but till then u can check taking pull. even i will do it

**Comment by PrakashDurlabhji** [comment]
@anonymousjaggu PR updated

**Comment by anonymousjaggu** [comment]
@PrakashDurlabhji Please read the description carefully 
image

You are making changes the wrong number of registrant you are doing a number of submission

**Comment by PrakashDurlabhji** [comment]
@anonymousjaggu updating in few minutes

**Comment by PrakashDurlabhji** [comment]
@anonymousjaggu PR updated

**Comment by anonymousjaggu** [comment]
> @anonymousjaggu PR updated

OK MR looks fine now

**Pull request merged**
