### PR TITLE
fix issue #894

### PR DESCRIPTION
**Pull request by suppermancool**
fix issue #894 
ABLE TO ADD INVALID OR INVALID FORMAT WEB URL IN ADD A WEB LINK.

### CODE REVIEW

**Comment by ThomasKranitsas** [comment]
@suppermancool this is not a correct way to do it. Now `google.com` is treated as an invalid URL while is valid.

Also, the `isWebLinkExist` function is causing the app to crash now. Can you please fix that?

**Comment by suppermancool** [comment]
@ThomasKranitsas isWebLinkExist is bind in constructor, so you need to refresh the page before testing. Anyway i will change isWebLinkExist to webLinkExist in this PR, and fix the logic for url, pls wait until i finish

**Comment by suppermancool** [comment]
@ThomasKranitsas i fixed the regex for url and change isWebLinkExist to webLinkExist, pls check, thanks

**Comment by ThomasKranitsas** [comment]
screen shot 2018-08-15 at 19 01 57


@suppermancool please see the above screenshot

**Comment by ThomasKranitsas** [comment]
Account: `TonyJ/appirio123`

**Pull request merged**
