### PR TITLE
[$50] - Error on accessing /my-submissions is not handled gracefully #696

### PR DESCRIPTION
**Pull request by ekundayo-ab**
### What does this PR do?
It ensures error thrown when a user tries to access a challenge where he/she is not registered is handled gracefully for best user experience

### Description of Task to be completed?
- Validate properties gotten from submission phase date before returning props
- Add a new case to access denied page template to check if a user has not registered for a challenge when trying to access the route, then give the appropriate graceful error message

### How should this be manually tested?
1. Pull in latest changes from remote repository to local repository
2. Fire up terminal run `npm install`
3. Run `npm run dev` to start up application in development environment
4. Visit url supplied by the application usually **http://localhost:3000**, navigate to login page
5. login with `username: dan_developer` and `password: dantopcoder123` for normal user access
6. Visit **all challenges** page, then view the challenge specs for one you've not registered in.
7. You should then see the graceful error message

### Any background context you want to provide?
The JavaScript breaks due to a property `actualStartTime` being accessed on a not-validated `submissionPhaseDate` object.

### What are the relevant issues tracker number?
[$50] - Error on accessing /my-submissions is not handled gracefully #696

### Screenshots (if appropriate)
screen shot 2018-01-10 at 11 52 26 am

### Questions:
If you have any question on this PR kindly comment below. Thanks

### CODE REVIEW

**Comment by ekundayo-ab** [comment]
@birdofpreyru can you kindly look at this pr #696 when you have a chance, so I know if need be to make some final fixes. Thanks

**Comment by birdofpreyru** [comment]
@ekundayo-ab sorry for the delay, I am having some problems to review all submitted PRs in timely manner. If necessary, I'll extend challenge timeline to ensure that everybody has enough time to do final fixes :)

**Comment by birdofpreyru** [comment]
@ekundayo-ab actually, the problem with crushes of the code still persists in your solution; e.g. try to login as TonyJ in dev environment and then go to http://local.topcoder.com/challenges/30058497/my-submissions, and *imadx* was the first to fix the underlying bug, so I've accepted his solution.

However, I like what you did. Now, with *imadx* fix applied, the page sometimes shows 404 error, sometimes non-authorized msg (see as TonyJ in dev:
http://local.topcoder.com/challenges/30058497/my-submissions and http://local.topcoder-dev.com:3000/challenges/30050464/my-submissions)

If you correct your solution to work properly in all cases, I can pay you $50 for this.
Let's do some changes though to what I see at your screenshot:
- The error text should read *You have not submitted to this challenge`
- The button text should read *Back to the challenge*
- Update related names in the code to match the usecase (`NOT_REGISTERED_FOR_CHALLENGE` should become `HAVE_NOT_SUBMITTED_TO_THE_CHALLENGE`).
- Use the standard primary button for the button (https://github.com/topcoder-platform/community-app/blob/develop/src/shared/components/buttons/index.jsx#L145)

**Comment by ekundayo-ab** [comment]
@birdofpreyru Thanks for the feedback I'll look into it and make necessary changes.

**Comment by ekundayo-ab** [comment]
@birdofpreyru I've looked into it and made the changes as you recommended.

I've updated the PR to include the screenshot of the error page. Do let me know if there is anything more I need to do.

Thanks

**Pull request merged**
