### PR TITLE
Fix msft 209 2

### PR DESCRIPTION
**Pull request by cunhavictor**
issue #2872

### CODE REVIEW

**Comment by veshu** [comment]
@sumitdaga Is there feedback here?

**Comment by codeMinter** [comment]
@cunhavictor stick to React Link

**Comment by codeMinter** [comment]
@cunhavictor PR has not been responded for 2 day now, if PR not updated in next 4-6 hrs, it will be marked open for pickup. We need to respond to feedback quick.

**Comment by veshu** [comment]
closing the PR as member didn't responded

**Pull request closed without merging**
