### PR TITLE
fixes #1480

### LINKED ISSUE #1480: Skill pager does not work on swipe left/right on iPhone
**Describe the bug**
Let's assume that the pager on the skills screen is at the right place. In mobile environment it is a usual practice to let these kind of pages change with swiping left or right. Here this is not possible.

**To Reproduce**
1. Go to 'https://www.topcoder.com/settings/profile'
2. Click on 'Skill'
3. Add at least 7 skills
4. Try swiping left/right on the list of skills 
5. See error

**Expected behavior**
The user should be able to use swiping to change pages.

**Screenshots** Cannot illustrate this, please try it yourself.
img_3897

**Smartphone:**
 - Device: iPhone 6s
 - OS: iOS 11
 - Browser: safari

@ThomasKranitsas

### PR DESCRIPTION
**Pull request by sumitdaga**
please note that the warnings in tests are not due to this fix but were already present!

### CODE REVIEW

**Comment by sumitdaga** [comment]
@ThomasKranitsas 

mind the new lib ...please run `npm i` first!

**Comment by ThomasKranitsas** [comment]
@sumitdaga can you please fix the merge conflicts?

**Comment by sumitdaga** [comment]
@ThomasKranitsas 
should be resolved!

**Comment by ThomasKranitsas** [comment]
@sumitdaga can you please center the content? There's too much gap on the right side.

**Comment by sumitdaga** [comment]
@ThomasKranitsas done!

**Pull request merged**
