### PR TITLE
community app issue-2853

### PR DESCRIPTION
**Pull request by nahidshahin**
issue #2853

### CODE REVIEW

**Comment by veshu** [comment]
@asadath1395 Can you pick this, any feedback here?

**Comment by asadath1395** [comment]
@veshu I left it actually because i didn't know how to configure local accounts app with community app

**Comment by veshu** [comment]
ok @codeMinter @sumitdaga please take this. Thanks!

**Comment by asadath1395** [comment]
@veshu I will give it a try one more time

**Pull request merged**
