### PR TITLE
WIP: Reskin for Unit Test Checking

### PR DESCRIPTION
**Pull request by dedywahyudi**

### CODE REVIEW

**Comment by dedywahyudi** [comment]
@luizrrodrigues @Oanh-and-only-Oanh 

It look these builds error not coming from the reskin code. 

Screen Shot 2022-05-17 at 17 21 20
Screen Shot 2022-05-17 at 17 21 28

Any ideas? 
Can you check please?

**Comment by luizrrodrigues** [comment]
@dedywahyudi looks like issue in CircleCI side, just tried to rerun a successful job but getting error.

https://app.circleci.com/pipelines/github/topcoder-platform/community-app/4244/workflows/50728f98-6f8a-420e-abab-734fefa1d6cb/jobs/14636/parallel-runs/0/steps/0-103

I'll try to check with support.

**Comment by dedywahyudi** [comment]
@luizrrodrigues 
New circleci issue
Screen Shot 2022-05-24 at 22 57 01

**Comment by luizrrodrigues** [comment]
@dedywahyudi looks like branch was deployed, please check if you see the chances.

**Comment by dedywahyudi** [comment]
@luizrrodrigues 

Ah okay, dev site have the updates!
So, what's wrong with that error?

**Pull request merged**
