### PR TITLE
Fix for issue #2638

### PR DESCRIPTION
**Pull request by lucyji1000**
Fix for [this issue](https://github.com/topcoder-platform/community-app/issues/2638).

Based on my understanding of the `Link` component in `topcoder-react-utils` from the docs [here](https://github.com/topcoder-platform/topcoder-react-utils/blob/master/docs/link-and-navlink.md), menu links in the `TopcoderHeader` component were setting the `enforceA` prop of the `Link` component to `true` and forcing a reload of the entire page.

### CODE REVIEW

**Comment by luizrrodrigues** [comment]
@lucyji1000 thanks, I'll review shortly

**Comment by ljipear** [comment]
@luizrrodrigues I based this PR off the `bug-bash` branch as specified in the challenge instructions, but I'm seeing some differences with the `feature-new-nav` branch like additional menu items in the `tc-communities/Header` component that may also be affected by the page reload issue -- should I have branched off the `feature-new-nav` branch instead?

**Comment by luizrrodrigues** [comment]
@ljipear Need to use `feature-new-nav` branch not `bug-bash`

**Comment by lucyji1000** [comment]
Ah I was working off the `bug-bash` branch, which did not have the new nav header. I switched to the `feature-new-nav` branch, and the issue is still there. 

It looks like the page reload is caused by the `TopNav` component in `navigation-component` rendering all menu links as `<a>` elements. Unfortunately I don't think I will be able to investigate this further in the time remaining -- you can close this PR and unassign me.

**Comment by luizrrodrigues** [comment]
@lucyji1000 Okay no problem, thanks for trying this. :)

**Pull request closed without merging**
