### PR TITLE
MSFT-17 & MSFT-35

### PR DESCRIPTION
**Pull request by r0hit-gupta**
changes for #2741 & #2757

### CODE REVIEW

**Comment by sushilshinde** [comment]
> changes for #2741 & #2757

@veshu @r0hit-gupta Please create separate PRs and close this one

**Comment by veshu** [comment]
@sushilshinde If there one line fix, separate PR won't be helpful?

**Comment by sushilshinde** [comment]
> @sushilshinde If there one line fix, separate PR won't be helpful?

So there two issues for the same change?

**Comment by veshu** [comment]
> So there two issues for the same change?

Yes, there are few issues which are fixed with same code.

**Pull request merged**
