### PR TITLE
Topcoder Member Profile UI Fixes and Enhancements - Part 2

### PR DESCRIPTION
**Pull request by nauhil**
https://www.topcoder.com/challenges/30092313

@gurmeetb Please check it

### CODE REVIEW

**Comment by gurmeetb** [comment]
@nauhil Thanks, can you please fix the lint issue, so we can merge this?

**Comment by nauhil** [comment]
OK

**Comment by nauhil** [comment]
@gurmeetb Checks passed. You can merge it

**Comment by gurmeetb** [comment]
Thanks @nauhil

**Pull request merged**
