### PR TITLE
fix issue #200

### PR DESCRIPTION
**Pull request by chqy24**
Fix issues #200

### CODE REVIEW

**Comment by birdofpreyru** [comment]
@chqy24 Nope, here we need a better fix. Look, the api v3 has been updated to get the following info for possible challenge types:
screenshot

Now, there is action / reducer to get challenge types for filters in challenge listing (maybe somewhere else), which uses v2 api. We should update those to use v3 api instead, without breaking existing code. Once we have it, we can get `subTrack` from v3 challenge details as it is, look for the matching challenge type, and get it proper human-readable name to render in the tag. Ideally, to make it efficient, when we fetch challenge types we should store them not only as an array (for challenge listing kind of use), but also like a map between subTrack and the object, so that we can lookup it efficiently.

**Comment by birdofpreyru** [comment]
@chqy24 Now it looks mostly cool, and challenge details page is perfect.
Though, I see some bugs with challenge details page:
1. When I select subtracks in the subtrack filter's dropdown for many of them no challenges match;
2. When I click subtrack tag in a challenge details page, it does take me to the challenge listing, with proper filter applied, and the filters count is set correctly, however, no filter is selected in the subtrack filter's dropdown (though filtering works properly even for those subtracks, that do not filter when I do 1).
Please, look into it to make it work properly. I expect, the fix should be trivial.

**Comment by chqy24** [comment]
I'd noticed these issues, but these are existed bugs and should be separated from #200

**Comment by birdofpreyru** [comment]
@chqy24 I really want them to be fixes as a part of this PR, so that we don't loose those a track of these issues. Under the hood, I believe, the only problem is that while now you properly fetch and use v3 subtrack keys in the challenge details page, in the challenge listing's dropdown the values from v2 are still used, so it causes the problem, as challenge objects, most probably, have sub track keys from v3.

So, the fix should be very easy. I can add $20 to the payment for cleaning this out.

**Comment by chqy24** [comment]
Sorry, you're right, The first issue was introduced by my previous commit
Please check it now.

**Pull request merged**
