### PR TITLE
issues-1305: Added Date picker and use at Birth Date

### PR DESCRIPTION
**Pull request by akmarif**
Added Date picker and use at Birth Date

Look of the date picker is now uniform across browsers. And at Edge in windows it's looks like this:
 
date_picker

### CODE REVIEW

**Comment by ThomasKranitsas** [comment]
Here's my review:

1. The input field doesn't match with the other input fields.
2. On mobile, the popup is a bit off-screen.

**Comment by akmarif** [comment]
working on it

**Comment by akmarif** [comment]
Hi @ThomasKranitsas
> The input field doesn't match with the other input fields.
 Fixed at 0c7b55e

> On mobile, the popup is a bit off-screen.
I'm using same `z-index: 2` and other style like the date-range-picker at filter page. Can you please check that date-range-picker? Is that also has the same problem? can you please give me a screenshot?

**Comment by ThomasKranitsas** [comment]
On mobile, there's no border

**Comment by akmarif** [comment]
@ThomasKranitsas can I reproduce at mobile view of chrome? Can you please give me a screenshot?

**Comment by ThomasKranitsas** [comment]
yeah, you can just resize your Chrome to reach the mobile breakpoint and you'll notice that the input doesn't match with the rest

**Comment by akmarif** [comment]
@ThomasKranitsas I just did what you said, but don't see the problem. Here is the screenshot:

screen shot 2018-09-28 at 8 53 00 pm

**Comment by ThomasKranitsas** [comment]
What do you mean you don't see the problem 🙂? Even in your screenshot, the birthdate input is way different than the other inputs (eg first name).

It shouldn't have that blueish background and it should have a border like the other fields.
Also, the font size and the padding is not correct.

**Comment by ThomasKranitsas** [comment]
I'm talking about the actual input. Not the popup.

**Comment by akmarif** [comment]
Ahh I see, fixing...

**Comment by akmarif** [comment]
@ThomasKranitsas please check again, gave a fix at 01e3b58

**Comment by ThomasKranitsas** [comment]
Don't worry about the `codacy/pr`. We don't use it.

**Comment by ThomasKranitsas** [comment]
Better but still not perfect.
- [ ] The font is wrong
- [ ] The padding is wrong
- [ ] The border is cut-off in the corners.

**Comment by akmarif** [comment]
@ThomasKranitsas 

> The font is wrong

Font fixed

>  The padding is wrong

Removed extra padding
 
> The border is cut-off in the corners.

border is better now

check at 548d357

**Pull request merged**
