### PR TITLE
Add X button to clear the challenge search.

### PR DESCRIPTION
**Pull request by narekcat**
I added X button to clear the challenge search as described in this issue: https://github.com/topcoder-platform/community-app/issues/3622.

### CODE REVIEW

**Comment by skyhit** [comment]
@narekcat tests failed, please check

**Comment by skyhit** [comment]
@narekcat for these .snap are they purposely to be changed? if not, why commit in this PR?

**Comment by narekcat** [comment]
@skyhit They purposed to be changed, because to add X button I added `span` tag in `ChallengeSearchBar.jsx` file and new property to `ChallengeFilters.jsx` file. But tests still fails, because `className`s has auto generated values. Now working on it.

**Comment by narekcat** [comment]
@skyhit I fixed tests issues.

**Pull request merged**
