### PR TITLE
Issue 166: Changed <a> header and challenge listing tags to <Link>

### PR DESCRIPTION
**Pull request by Colinh84**
https://github.com/topcoder-platform/community-app/issues/166

### CODE REVIEW

**Comment by birdofpreyru** [comment]
@Colinh84 I have left a comment on code. Have not tried to run your code, but it looks fine otherwise. Have you checked, that this change does not affect styling?

**Comment by Colinh84** [comment]
@birdofpreyru The styling is not affected by these changes.

**Comment by Colinh84** [comment]
@birdofpreyru completed requested change to branch.

**Comment by birdofpreyru** [comment]
@Colinh84 Oh, actually, this PR broke some unit tests because:
1. You had to update snapshots for snapshot tests (doing `npm run jest -- -u` after ensuring that only relevant snapshots have been affected by your changes).
2. Ensure that all components containing the new links get a mock Redux store during unit tests.

Well, as I have already accepted your PR, and these fixes are no that big, I'll just fix myself.

**Pull request merged**
