### PR TITLE
MSFT-153

### PR DESCRIPTION
**Pull request by r0hit-gupta**
changes for #2843

### CODE REVIEW

**Comment by r0hit-gupta** [comment]
Please retrigger the build. The build failed due to some internal error on Circle CI.

**Comment by codeMinter** [comment]
@r0hit-gupta fix goes in `react-ui`

**Comment by r0hit-gupta** [comment]
@codeMinter done

**Comment by sushilshinde** [comment]
@codeMinter @r0hit-gupta what's the PR number of `react-ui` associated with

**Comment by codeMinter** [comment]
> @codeMinter @r0hit-gupta what's the PR number of `react-ui` associated with

uses existing variable so no PR needed.

**Pull request merged**
