### PR TITLE
issue_1162 basic info validation fixed

### PR DESCRIPTION
**Pull request by Gauravseta**

### CODE REVIEW

**Comment by Gauravseta** [comment]
@ThomasKranitsas i am resolving conflicts

**Comment by ThomasKranitsas** [comment]
can you please fix the failing tests

**Comment by Gauravseta** [comment]
@ThomasKranitsas yes working on it

**Comment by ThomasKranitsas** [comment]
seems like they failed again

**Comment by Gauravseta** [comment]
@ThomasKranitsas now it wont for sure. resolved js linting.

**Pull request merged**
