### PR TITLE
Added month & year selector at date picker

### PR DESCRIPTION
**Pull request by nahidshahin**
Added month & year selector at date picker

### CODE REVIEW

**Comment by ThomasKranitsas** [comment]
1. Please remove the border from the mobile view.
screenshot 2018-11-27 at 16 41 10

2. Please make sure other pages that use the same date picker package work fine. Currently, the challenges page is broken.
screenshot 2018-11-27 at 16 42 13

3. Can you fix the failed tests?

**Comment by ThomasKranitsas** [comment]
There are some minor styling issues. Please compare with the current version from here https://www.topcoder.com/challenges

1. The day numbers are off-center
2. Remove the outline
3. Remove the border

screenshot 2018-11-27 at 17 15 10

**Comment by nahidshahin** [comment]
@ThomasKranitsas 3 UI issues addressed at 5186e4f

**Comment by ThomasKranitsas** [comment]
Will check shortly

**Comment by ThomasKranitsas** [comment]
One last fix. Please change the font family of the date picker in the settings page to match with the rest of the page.

**Comment by nahidshahin** [comment]
@ThomasKranitsas I see exactly the same font at settings page. That is:
```
    font-size: 15px;
    font-family: "Roboto", Helvetica, Arial, sans-serif;
    font-weight: 400;
```

Compared with last name field and I found no difference:
screen shot 2018-11-28 at 7 29 33 am

I don't understand what exactly you are looking for?

**Comment by nahidshahin** [comment]
ahh, I see, you mean the pop-up. Fixing it too.

**Comment by nahidshahin** [comment]
@ThomasKranitsas fixed the font, please check:
screen shot 2018-11-28 at 7 44 43 am

**Pull request merged**
