### PR TITLE
MSFT-102

### PR DESCRIPTION
**Pull request by r0hit-gupta**
Changes for #2806

### CODE REVIEW

**Comment by veshu** [comment]
@r0hit-gupta @luizrrodrigues This needs following support
1. tab support
2. role should be added with "contentinfo"

**Comment by r0hit-gupta** [comment]
@veshu i have added tab support but with the role as `figure` because as per https://www.w3.org/TR/wai-aria-practices/examples/landmarks/contentinfo.html , role `contentinfo` should be used generally for footer. Please review. Thanks!

**Comment by luizrrodrigues** [comment]
@veshu @r0hit-gupta 
This not working to me.

Note read:
- Ends Jul 30
- Currently phase
- Currenlty phase deadline

Wrong read:
- $200 Purse - Reading "Plus Dollar Tow Hundred"
- Number os submission: "Zero Link"

**Comment by r0hit-gupta** [comment]
@luizrrodrigues which reader are you using?

**Comment by luizrrodrigues** [comment]
@r0hit-gupta Windows and JAWS readers.

**Comment by r0hit-gupta** [comment]
@veshu which reader did you use?

**Comment by veshu** [comment]
@r0hit-gupta @luizrrodrigues I used to NVDA before, just checked with JAWS as well. it is reading correctly per steps.

It is saying as "Purse $ 200, figure"

**Comment by luizrrodrigues** [comment]
@veshu Yeah, my fault in typing:
"Purse Dollar Two Hundred"

but right read need by:
“Two hundred dollar purse” I think.

And see missing read too:
- Ends Jul 30
- Currently phase
- Currenlty phase deadline

And wrong to submissions:
- Number os submission: “Zero Link”

**Pull request merged**
