### PR TITLE
add csp header for tco

### PR DESCRIPTION
**Pull request by eisbilir**

### CODE REVIEW

**Comment by eisbilir** [comment]
@luizrrodrigues I added csp header for `tco**.topcoder.com`. It looks 90% similar with the ones for veterans. Do you think I should combine them or keep them separate?

**Comment by luizrrodrigues** [comment]
@eisbilir yep, combine both will be better.

**Comment by eisbilir** [comment]
@luizrrodrigues it's ready.

**Review by luizrrodrigues — APPROVED** [review]

**Comment by luizrrodrigues** [comment]
@eisbilir Thanks, I'll deploy to QA.

Can you link the Jira ticket to issue please?

**Comment by eisbilir** [comment]
https://github.com/topcoder-platform/community-app/issues/6362

**Comment by luizrrodrigues** [comment]
@eisbilir Moved to feature branch: https://github.com/topcoder-platform/community-app/tree/fix-security-headers

**Pull request merged**
