### PR TITLE
issue #5501 fix: member country is not displayed in settings

### PR DESCRIPTION
**Pull request by gets0ul**
#5501 
use homeCountryCode or competitionCountryCode as displayed country in member settings page when country is not found in the basic_info traits

### CODE REVIEW

**Review by luizrrodrigues — CHANGES_REQUESTED** [review]
@gets0ul If try to edit any field will show error message in Country field:
https://i.gyazo.com/e9c82a736649ac24d292a15cb5fbe0f6.mp4

**Comment by sushilshinde** [comment]
> @gets0ul If try to edit any field will show error message in Country field:
> https://i.gyazo.com/e9c82a736649ac24d292a15cb5fbe0f6.mp4

@gets0ul can you finish this today?

**Comment by gets0ul** [comment]
@luizrrodrigues Yes, will update it ASAP

**Comment by gets0ul** [comment]
@luizrrodrigues @sushilshinde Updated

**Comment by luizrrodrigues** [comment]
@gets0ul Thanks, checking.

**Review by luizrrodrigues — APPROVED** [review]

**Pull request merged**
