### PR TITLE
Issue 329

### LINKED ISSUE #329: [$20] - Clearing search and search using empty field won't remove the previous search term from the URL
Steps to Reproduce
-----------------------------------------------------------------

- Login as a valid user

- Go to http://community-app.topcoder.com/challenges

- enter '*^&%&^%^&%&(%(%' and search

- Now delete the *^&%&^%^&%&(%(% text and click search

- Page will return to the Challenge listing page but the URL http://community-app.topcoder.com/challenges?%[0]=&%[1]=&^%^=&(%(%=

Actual Result(s)
-----------------------------------------------------------------
- Clearing search and search using empty field won't remove the previous search term from the URL
- http://community-app.topcoder.com/challenges?^^$%^$)(*^=&^=

Expected Result(s)
-----------------------------------------------------------------
- Must clear the search term from URL and display as http://community-app.topcoder.com/challenges

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 64bit
- **Browser(s):** Chrome 60.0.3112.101 (Official Build) (64-bit)

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------

### PR DESCRIPTION
**Pull request by shubhendusaurabh**
fixed #329 escape query text for searching

### CODE REVIEW

**Comment by birdofpreyru** [comment]
@shubhendusaurabh I don't like the points where you do encoding / decoding. I believe, the best point to encode is https://github.com/topcoder-platform/community-app/blob/develop/src/shared/reducers/challenge-listing/index.js#L168, and the best point to decode is https://github.com/topcoder-platform/community-app/blob/develop/src/shared/reducers/challenge-listing/index.js#L272 this way it will automatically work in all other code dealing with search by text. Please update and test

**Comment by shubhendusaurabh** [comment]
@birdofpreyru Is the challenges page on latest develop branch broken? It was working yesterday.
filter
querydate

**Comment by twicoder** [comment]
@shubhendusaurabh  I will fix it

**Comment by twicoder** [comment]
@birdofpreyru  Please check PR #421 for the update of issue 212.

**Comment by birdofpreyru** [comment]
@shubhendusaurabh Sorry, will have to reject this and close the original issue. The problem was fixed by a change done elsewhere. The trick, actually, was in adding the proper option `{ encodeValuesOnly: true }` here: https://github.com/topcoder-platform/community-app/blob/develop/src/shared/utils/url.js#L31

Before it was naively configured to not encode params written to query, which caused this problem (just leaving stringify with default options is also not that good, as it replaces square brackets `[..]` in filter elements, which makes it more difficult to understand the query).

**Pull request closed without merging**
