### PR TITLE
Fix issue #303

### PR DESCRIPTION
**Pull request by twicoder**

### CODE REVIEW

**Comment by birdofpreyru** [comment]
1. Have not actually tried to launch your fix, just looking into the code, I see, that it probably makes the trick right, but, please, re-write it to make necessary date/time formatting with `momentjs` (https://momentjs.com/docs/). I believe, it will be a way more compact, and a way less error-prone.

2. Also pay attention that these changes break some snapshot-based unit tests - should be fixed.

**Comment by birdofpreyru** [comment]
@twicoder

**Comment by twicoder** [comment]
@birdofpreyru  I have changed the code but can't find a proper method to format duration.

**Comment by birdofpreyru** [comment]
@twicoder eh... https://momentjs.com/docs/#/displaying/format/ doesn't it cover our needs here?

**Comment by twicoder** [comment]
@birdofpreyru The expected fix is show duration as “??d ??h” or “??h ??mim” or “??min ??s”, and I find the format function of moment can’t cover this well.

**Pull request merged**
