### PR TITLE
Fix for issues-2179

### PR DESCRIPTION
**Pull request by nahidshahin**
Showing Country Rank `-` if servers returns 0

### CODE REVIEW

**Comment by nahidshahin** [comment]
@sexta13 
> I would do a different check. Something like x ? x : '-'.

I guess we don't need ternary operator at all, this one should work `x || '-'`

**Comment by sexta13** [comment]
> @sexta13
> 
> > I would do a different check. Something like x ? x : '-'.
> 
> I guess we don't need ternary operator at all, this one should work `x || '-'`

True :) Well done

**Comment by ThomasKranitsas** [comment]
@sexta13 how come you reviewed this one? 🙂

**Comment by sexta13** [comment]
@thomaskranitsas.. I just commented because I was going to pick this one... But once I saw the issue was coming from the API..and in the issue there was no "expected result"... I came to see what was the implementation :) I just gave my 5cents of opinion eheh

**Pull request merged**
