### PR TITLE
MSFT-186

### PR DESCRIPTION
**Pull request by r0hit-gupta**
Changes for #2854

### CODE REVIEW

**Comment by anonymousjaggu** [comment]
@r0hit-gupta Please check the video carefully, it's under the share section but you are referring here in the footer section

**Comment by veshu** [comment]
@r0hit-gupta Please check this asap, its already 2 days. Thanks!

**Comment by r0hit-gupta** [comment]
@veshu sorry for the dealy. Resolving right now. Thanks.

**Comment by r0hit-gupta** [comment]
@anonymousjaggu @veshu resolved. Please review.

**Comment by anonymousjaggu** [comment]
@r0hit-gupta please check the `MR` 
image

It has some issues please fix this

**Comment by r0hit-gupta** [comment]
@anonymousjaggu please check now.

**Comment by anonymousjaggu** [comment]
@r0hit-gupta still facing the same error better create new MR and assign it to me
Thanks

**Comment by r0hit-gupta** [comment]
@anonymousjaggu done. PR at https://github.com/topcoder-platform/community-app/pull/3126

**Pull request closed without merging**
