### PR TITLE
Deep link profile

### LINKED ISSUE #2122: [$100] Profile Settings: Reloading the "Communities" page redirects to "Basic Info" page
**Steps to Reproduce**

1. Go to user's profile settings page-->Basic info (https://www.topcoder-dev.com/settings/profile)
2. Click on 'Communities' tab on left side
3. Select/Un-Select any community and check save status message at the top
4. Reload the page to check whether Communities check box button states are saved properly or not

**Actual Behaviour**
Reloading the "Communities" page redirects to "Basic Info" page. Should have seperate page or marker in url to avoid this issue(ex: https://www.topcoder-dev.com/settings/**profile#communities**)

**Expected behavior**
Reloading Should launch same page, Should have separate page or marker in URL to navigate to same page that uer is working on currently(ex: https://www.topcoder-dev.com/settings/**profile#communities**)

**Screen shots/video**
https://dl.dropboxusercontent.com/s/sdo0ftifcv29jit/w4ACj0B0Hm.mp4

**Environment (please complete the following information):**
Dell Vostro 2520; Windows 10 | Browser: Google Chrome 73.0.3683.75 (Official Build) (64-bit)
 
**Reproducible rate**
3/3

### PR DESCRIPTION
**Pull request by r0hit-gupta**
Fixes #2122

### CODE REVIEW

**Comment by ThomasKranitsas** [comment]
@r0hit-gupta can you please do the same for `Tools` and `Account`?

**Comment by ThomasKranitsas** [comment]
@r0hit-gupta please read my message above

**Comment by r0hit-gupta** [comment]
@ThomasKranitsas yes I can do that. But those are stateless functional components and need to be converted to stateful components. Can you please raise the ticket prize to include Tools and Account? Thanks.

**Comment by ThomasKranitsas** [comment]
Sure, I will raise the prize. No problem.

**Comment by r0hit-gupta** [comment]
Please review.

**Pull request merged**
